import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { checkBranch, checkMessage, commitMessagesInRange, run } from './check-attribution.mjs';

const script = fileURLToPath(new URL('./check-attribution.mjs', import.meta.url));
const reasons = text => checkMessage(text).map(v => v.reason);

test('rejects AI co-author trailers in any casing', () => {
  assert.deepEqual(reasons('fix: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>'), ['AI co-author trailer']);
  assert.deepEqual(reasons('fix: x\n\nco-authored-by: Codex <codex@users.noreply.github.com>'), ['AI co-author trailer']);
  assert.deepEqual(reasons('fix: x\n\nCo-authored-by: Bot <noreply@openai.com>'), ['AI co-author trailer']);
  assert.deepEqual(reasons('fix: x\n\nCo-authored-by: Cursor Agent <cursoragent@cursor.com>'), ['AI co-author trailer']);
});

test('allows human and dependency-bot co-authors', () => {
  assert.deepEqual(reasons('Bump x\n\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>\nCo-authored-by: teaqu <583418+teaqu@users.noreply.github.com>'), []);
});

test('rejects AI generation footers and robot markers', () => {
  assert.deepEqual(reasons('Summary\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_'), ['AI generation footer']);
  assert.deepEqual(reasons('Generated with ChatGPT'), ['AI generation footer']);
  assert.deepEqual(reasons('🤖 Some footer'), ['AI generation marker']);
});

test('does not mistake ordinary wording for attribution', () => {
  assert.deepEqual(reasons('host-functions.js was generated without the websocket-origin callbacks'), []);
  assert.deepEqual(reasons('the file is generated by generate-host-functions.mjs'), []);
  assert.deepEqual(reasons('Keep the cursor in place when the preview opens'), []);
  assert.deepEqual(reasons('claude md link because they do not link standards'), []);
  assert.deepEqual(reasons('Also removes Co-Authored-By from commit metadata.'), []);
});

test('rejects merge subjects that name agent branches, source or target', () => {
  assert.deepEqual(reasons("Merge branch 'codex/reset-atomic' into wgsl"), ['agent-named branch in merge subject']);
  assert.deepEqual(reasons("Merge remote-tracking branch 'origin/main' into claude/issue-270"), ['agent-named branch in merge subject']);
  assert.deepEqual(reasons("Merge remote-tracking branch 'origin/copilot/fix' into main"), ['agent-named branch in merge subject']);
  assert.deepEqual(reasons("Merge remote-tracking branch 'origin/main' into issue-270-gpu-e2e-flakes"), []);
});

test('rejects agent-prefixed branch names only', () => {
  assert.equal(checkBranch('claude/issue-270').length, 1);
  assert.equal(checkBranch('refs/heads/codex-fix').length, 1);
  assert.equal(checkBranch('Copilot_patch').length, 1);
  assert.deepEqual(checkBranch('issue-270-gpu-readback'), []);
  assert.deepEqual(checkBranch('cursor-position-fix'), []);
  assert.deepEqual(checkBranch('fix-claude-md-link'), []);
});

test('run labels findings by where they were found', () => {
  const findings = run(
    ['--message-file', 'MSG', '--range', 'a..b', '--branch', 'claude/x', '--text', 'PR body=🤖 hi', '--text', 'bare 🤖'],
    {
      readFile: () => 'fix\n# Co-authored-by: Claude <noreply@anthropic.com>\n',
      commits: range => {
        assert.equal(range, 'a..b');
        return [{ sha: '0123456789abcdef', message: 'x\n\nCo-authored-by: Claude <noreply@anthropic.com>' }];
      },
    },
  );
  assert.deepEqual(findings.map(f => f.where), ['commit 01234567', 'branch', 'PR body', 'text']);
});

test('run ignores git comment lines in a commit message file', () => {
  assert.deepEqual(run(['--message-file', 'MSG'], { readFile: () => '# 🤖 comment only\nfix\n' }), []);
});

test('run rejects unknown options and missing values', () => {
  assert.throws(() => run(['--nope', 'x']), /unknown option --nope/);
  assert.throws(() => run(['--branch']), /--branch needs a value/);
});

test('commitMessagesInRange splits git log output per commit', () => {
  const output = 'aaa\x00first\n\nbody\n\x01\nbbb\x00second\n\x01\n';
  const commits = commitMessagesInRange('x..y', (cmd, args) => {
    assert.equal(cmd, 'git');
    assert.equal(args.at(-1), 'x..y');
    return output;
  });
  assert.deepEqual(commits, [
    { sha: 'aaa', message: 'first\n\nbody\n' },
    { sha: 'bbb', message: 'second\n' },
  ]);
});

test('the commit-msg hook blocks an attributed commit and allows a clean one', () => {
  const repo = mkdtempSync(join(tmpdir(), 'attribution-'));
  const git = (...args) => spawnSync('git', ['-C', repo, ...args], { encoding: 'utf8' });
  execFileSync('git', ['init', '-q', repo]);
  git('config', 'user.email', 'test@example.com');
  git('config', 'user.name', 'Test');
  git('config', 'core.hooksPath', fileURLToPath(new URL('.', import.meta.url)));
  // The hook resolves the checker from the repository root.
  execFileSync('mkdir', ['-p', join(repo, '.githooks')]);
  execFileSync('cp', [script, join(repo, '.githooks')]);
  writeFileSync(join(repo, 'f'), '1');
  git('add', 'f');

  const blocked = git('commit', '-q', '-m', 'fix: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>');
  assert.notEqual(blocked.status, 0);
  assert.match(blocked.stderr, /AI co-author trailer/);

  const allowed = git('commit', '-q', '-m', 'fix: x');
  assert.equal(allowed.status, 0, allowed.stderr);
});

test('the CLI exits 1 with a report on violations and 2 on bad usage', () => {
  const bad = spawnSync(process.execPath, [script, '--branch', 'claude/x'], { encoding: 'utf8' });
  assert.equal(bad.status, 1);
  assert.match(bad.stderr, /branch: agent name in branch name: claude\/x/);
  assert.equal(spawnSync(process.execPath, [script, '--branch', 'fix-x']).status, 0);
  assert.equal(spawnSync(process.execPath, [script, '--bogus', 'x']).status, 2);
});
