import { test, expect } from '@playwright/test';
import { workspace } from './language-service-fixtures.mjs';
test('standalone Select reuses workspace files and config file choices persist', async ({ page }) => {
 await page.route('**/__select_fixture__', route => route.fulfill({ contentType: 'text/html', body: '<title>Fixture</title>' }));
 await page.goto('/__select_fixture__');
 const source = 'fn mainImage(coord: vec2f) -> vec4f { return vec4f(1); }';
 await workspace(page, [['reuse.wgsl', source], ['existing.wgsl', source + '\n@vertex fn separateVertex() -> @builtin(position) vec4f { return vec4f(0); }'], ['reuse.sha.json', JSON.stringify({ version:'1.0', passes:{ Image:{}, BufferA:{path:''}, BufferB:{path:'existing.wgsl'} } })]]);
 await page.goto('/');
 await page.getByTestId('shader-option-reuse-wgsl').click();
 await page.getByTestId('web-preview').getByLabel('Toggle config panel').click();
 await page.getByRole('button', {name:'BufferA Remove BufferA',exact:true}).click();
 const main=page.locator('.tab-content .buffer-details > .config-item').first();
 await main.getByLabel('Shader file').selectOption('existing.wgsl');
 await expect(main.getByLabel('Shader file')).toHaveValue('existing.wgsl');
 await expect(main.locator('.config-input')).toHaveCount(0);
 await main.getByLabel('Shader file').selectOption('custom');
 await main.getByRole('button',{name:'Browse',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Select workspace file'});
 await expect(dialog).toBeVisible();
 await dialog.getByLabel('Filter files').fill('existing');
 await dialog.getByRole('button',{name:'/shaders/existing.wgsl',exact:true}).click();
 await expect(main.getByLabel('Shader file')).toHaveValue('/shaders/existing.wgsl');
 await main.getByLabel('Shader file').selectOption('/shaders/reuse.wgsl');
 await page.getByLabel('Geometry',{exact:true}).selectOption('cube');
 const vertex=page.locator('.config-item').filter({has:page.getByRole('heading',{name:'Vertex shader',exact:true})});
 await expect(vertex.getByLabel('Vertex source')).toHaveValue('builtin');
 await vertex.getByLabel('Vertex source').selectOption('custom');
 await vertex.getByRole('button',{name:'Select',exact:true}).click();
 await page.getByRole('dialog',{name:'Select workspace file'}).getByRole('button',{name:'/shaders/existing.wgsl',exact:true}).click();
 await expect(vertex.locator('.config-input')).toHaveValue('/shaders/existing.wgsl');
 await expect(page.getByLabel('Vertex function',{exact:true}).locator('option[value="separateVertex"]')).toHaveCount(1);
 const functions=page.getByRole('group',{name:'Vertex function controls'});
 await functions.getByLabel('Insert mode').selectOption('native');
 await functions.getByRole('button',{name:'Add',exact:true}).click();
 await expect.poll(async()=>(await workspace(page))['/shaders/existing.wgsl']).toContain('BufferAVertex');
 expect((await workspace(page))['/shaders/reuse.wgsl']).toBe(source);
 await vertex.getByLabel('Vertex source').selectOption('builtin');
 await expect(vertex.locator('.config-input')).toHaveCount(0);
 await vertex.getByLabel('Vertex source').selectOption('same');
 await expect(vertex.locator('.config-input')).toHaveCount(0);
 await page.getByLabel('Output format',{exact:true}).selectOption('rgba16float');
 expect(await page.locator('.resolution-section').getByLabel('Output format').count()).toBe(1);
 await expect.poll(async()=>JSON.parse((await workspace(page))['/shaders/reuse.sha.json']).passes.BufferA.path).toBe('/shaders/reuse.wgsl');
 expect((await workspace(page))['/shaders/reuse.wgsl']).toBe(source);
 await page.reload();
 expect(JSON.parse((await workspace(page))['/shaders/reuse.sha.json']).passes.BufferA).toMatchObject({path:'/shaders/reuse.wgsl',outputFormat:'rgba16float',vertex:'/shaders/reuse.wgsl'});
});
