import * as path from 'path';
import {
  buildGlslCompatibilityUniformDeclarationLines,
  GLSL_STABLE_DECLARATION_LINES,
  GLSL_STABLE_NAMES,
  resolveGlslInputBindings,
} from '@shader-studio/types';
import type { GlslInputLike } from '@shader-studio/types';

export interface ShaderValidatorPreambleSnapshot {
  shaderPath: string;
  configPath: string | null;
  passName: string;
  inputs?: Readonly<Record<string, GlslInputLike>>;
  customUniformDeclarations?: string;
}

export type ShaderValidatorPreamblePreparation =
  | { kind: 'valid'; snapshot: ShaderValidatorPreambleSnapshot }
  | { kind: 'invalid'; shaderPath: string };

export interface ShaderValidatorPreambleBuildResult {
  content: string;
  warnings: string[];
}

const CUSTOM_UNIFORM_PATTERN = /^\s*uniform\s+(float|vec2|vec3|vec4|bool)\s+([A-Za-z_]\w*)\s*;\s*$/;

function sanitizeMetadata(value: string): string {
  return value.replace(/[\r\n]+/g, ' ').replace(/\*\//g, '').trim();
}

function commentSafeBasename(filePath: string): string {
  return sanitizeMetadata(path.basename(filePath));
}

function customUniformLines(
  declarations: string | undefined,
  ownedNames: Set<string>,
  warnings: string[],
): string[] {
  if (!declarations) {
    return [];
  }

  const lines: string[] = [];
  for (const declaration of declarations.split(/\r?\n|\r/)) {
    if (!declaration.trim()) {
      continue;
    }

    const match = declaration.match(CUSTOM_UNIFORM_PATTERN);
    if (!match) {
      warnings.push(`Invalid custom uniform declaration omitted: ${declaration.trim()}`);
      continue;
    }

    const [, type, name] = match;
    if (ownedNames.has(name)) {
      warnings.push(`Custom uniform "${name}" conflicts with an existing GLSL name and was omitted.`);
      continue;
    }

    ownedNames.add(name);
    lines.push(`uniform ${type} ${name};`);
  }

  return lines;
}

export function buildShaderValidatorPreamble(
  snapshot: ShaderValidatorPreambleSnapshot,
): ShaderValidatorPreambleBuildResult {
  const warnings: string[] = [];
  const bindings = resolveGlslInputBindings(snapshot.inputs);
  const channelCount = Math.max(4, bindings.length);
  const slotTypes = Array.from({ length: channelCount }, (_, slot) => (
    bindings[slot]?.samplerType ?? 'sampler2D'
  ));
  const ownedNames = new Set<string>([
    ...GLSL_STABLE_NAMES,
    'iChannelResolution',
    'iCh0',
    'iCh1',
    'iCh2',
    'iCh3',
    ...Array.from({ length: channelCount }, (_, slot) => `iChannel${slot}`),
  ]);
  const aliasLines: string[] = [];

  for (const binding of bindings) {
    if (!binding.isCustomName) {
      continue;
    }

    if (ownedNames.has(binding.key)) {
      warnings.push(`Input alias "${binding.key}" conflicts with an existing GLSL name and was omitted.`);
      continue;
    }

    ownedNames.add(binding.key);
    aliasLines.push(`uniform ${binding.samplerType} ${binding.key};`);
  }

  const lines = [
    '// Generated by Shader Studio; do not edit.',
    `// Active shader: ${commentSafeBasename(snapshot.shaderPath)}`,
    `// Config: ${snapshot.configPath === null ? 'none' : commentSafeBasename(snapshot.configPath)}`,
    `// Pass: ${sanitizeMetadata(snapshot.passName)}`,
    '',
    ...GLSL_STABLE_DECLARATION_LINES,
    '',
    ...slotTypes.map((samplerType, slot) => `uniform ${samplerType} iChannel${slot};`),
    ...aliasLines,
    `uniform vec3 iChannelResolution[${channelCount}];`,
    '',
    ...buildGlslCompatibilityUniformDeclarationLines(slotTypes),
  ];
  const customLines = customUniformLines(snapshot.customUniformDeclarations, ownedNames, warnings);
  if (customLines.length > 0) {
    lines.push('', ...customLines);
  }

  // Shader Validator 1.4.3 drops a preamble that ends in a newline; keep this
  // newline-free until its upstream loader is fixed.
  return { content: lines.join('\n'), warnings };
}
