import { createHash } from "crypto";
import * as path from "path";
import * as vscode from "vscode";
import { SlangEditorContextProvider } from "./SlangEditorContextProvider";
import { buildSlangEditorContextModule } from "./SlangEditorContextModule";

const CONFIGURE_COMMAND = "shader-studio.configureSlangFocusContextPoc";
const OFFICIAL_SLANG_EXTENSION_ID = "shader-slang.slang-language-extension";

type FocusContextLogger = Pick<vscode.LogOutputChannel, "info" | "warn" | "error">;
type FocusContextFileSystem = Pick<vscode.FileSystem, "createDirectory" | "writeFile">;

export interface SlangFocusContextSourceProvider {
  buildSource(document: vscode.TextDocument): Promise<string>;
}

export function sanitizeSlangIdentifier(value: string): string {
  const sanitized = value.replace(/[^A-Za-z0-9_]/g, "_");
  if (!sanitized) {
    return "shader";
  }

  return /^[0-9]/.test(sanitized) ? `_${sanitized}` : sanitized;
}

export function buildSlangFocusModule(fileName: string): string {
  const baseName = path.basename(fileName, path.extname(fileName));
  const identifier = sanitizeSlangIdentifier(baseName);

  return [
    "// Generated by Shader Studio Slang focus context PoC. Do not edit.",
    "#language slang 2026",
    "module shader_studio;",
    "",
    `public static const float shaderStudioFocus_${identifier} = 1.0;`,
    "",
  ].join("\n");
}

function comparablePath(value: string): string {
  const resolved = path.resolve(value);
  return process.platform === "win32" ? resolved.toLowerCase() : resolved;
}

export function mergeSearchPath(
  existingPaths: readonly string[],
  generatedPath: string,
): string[] {
  const comparableGeneratedPath = comparablePath(generatedPath);
  if (existingPaths.some((value) => comparablePath(value) === comparableGeneratedPath)) {
    return [...existingPaths];
  }

  return [...existingPaths, generatedPath];
}

export function workspaceContextKey(
  workspaceFolders: readonly vscode.WorkspaceFolder[],
): string {
  const workspaceIdentity = workspaceFolders
    .map((folder) => folder.uri.toString())
    .sort()
    .join("\n");

  return createHash("sha256").update(workspaceIdentity).digest("hex").slice(0, 12);
}

export class SlangFocusContextPoc implements vscode.Disposable {
  private readonly disposables: vscode.Disposable[] = [];
  private generatedDocument: vscode.TextDocument | undefined;
  private lastGeneratedSource: string | undefined;
  private focusTimer: NodeJS.Timeout | undefined;
  private generatedUri: vscode.Uri | undefined;
  private focusedDocument: vscode.TextDocument | undefined;
  private configured = false;

  constructor(
    private readonly context: vscode.ExtensionContext,
    private readonly logger: FocusContextLogger,
    private readonly debounceMs = 150,
    private readonly fileSystem: FocusContextFileSystem = vscode.workspace.fs,
    private readonly sourceProvider: SlangFocusContextSourceProvider = new SlangEditorContextProvider(),
  ) {
    this.disposables.push(
      vscode.commands.registerCommand(CONFIGURE_COMMAND, () => this.configure()),
      vscode.workspace.onDidChangeConfiguration((event) => {
        if (!event.affectsConfiguration("shader-studio.slangEditorIntegration")) {
          return;
        }
        if (this.isIntegrationEnabled()) {
          void this.configure(false);
        } else {
          this.disable();
        }
      }),
      vscode.window.onDidChangeActiveTextEditor((editor) => {
        this.handleEditorFocus(editor);
      }),
      vscode.workspace.onDidChangeTextDocument((event) => {
        this.handleContextDocumentChange(event);
      }),
    );
    void this.configure(false);
  }

  public dispose(): void {
    if (this.focusTimer) {
      clearTimeout(this.focusTimer);
      this.focusTimer = undefined;
    }
    for (const disposable of this.disposables) {
      disposable.dispose();
    }
  }

  private async configure(showMissingExtensionMessage = true): Promise<void> {
    if (!this.isIntegrationEnabled()) {
      if (showMissingExtensionMessage) {
        await vscode.window.showInformationMessage(
          "Enable Shader Studio's Slang editor integration in Settings before configuring it.",
        );
      }
      return;
    }

    if (!vscode.extensions.getExtension(OFFICIAL_SLANG_EXTENSION_ID)) {
      if (!showMissingExtensionMessage) {
        return;
      }
      const selection = await vscode.window.showInformationMessage(
        "The official Slang extension is required for Slang editor support.",
        "Open Extension",
      );
      if (selection === "Open Extension") {
        await vscode.commands.executeCommand(
          "workbench.extensions.search",
          `@id:${OFFICIAL_SLANG_EXTENSION_ID}`,
        );
      }
      return;
    }

    const workspaceFolders = vscode.workspace.workspaceFolders ?? [];
    if (workspaceFolders.length === 0) {
      await vscode.window.showErrorMessage(
        "Open a workspace before configuring Slang focus context.",
      );
      return;
    }

    try {
      const generatedDirectory = vscode.Uri.joinPath(
        this.context.globalStorageUri,
        "slang-focus-context",
        workspaceContextKey(workspaceFolders),
      );
      const generatedUri = vscode.Uri.joinPath(
        generatedDirectory,
        "shader-studio.slang",
      );
      this.generatedUri = generatedUri;
      const configuration = vscode.workspace.getConfiguration("slang");
      const existingPaths = configuration.get<string[]>(
        "additionalSearchPaths",
        [],
      );
      const searchPaths = mergeSearchPath(existingPaths, generatedDirectory.fsPath);

      await configuration.update(
        "additionalSearchPaths",
        searchPaths,
        vscode.ConfigurationTarget.Workspace,
      );
      await this.fileSystem.createDirectory(generatedDirectory);

      const activeDocument = vscode.window.activeTextEditor?.document;
      const focusedDocument = isSlangDocument(activeDocument)
        && !this.isGeneratedDocument(activeDocument)
        ? activeDocument
        : undefined;
      const source = focusedDocument
        ? await this.sourceProvider.buildSource(focusedDocument)
        : buildSlangEditorContextModule({
          focusedFileName: "shader.slang",
          channels: [],
          customUniforms: [],
        });
      await this.fileSystem.writeFile(generatedUri, Buffer.from(source, "utf8"));
      this.generatedDocument = await vscode.workspace.openTextDocument(generatedUri);
      this.focusedDocument = focusedDocument;
      this.lastGeneratedSource = source;
      this.configured = true;

      this.logger.info(
        `Configured Slang focus context module at ${generatedUri.fsPath}`,
      );
      await vscode.window.showInformationMessage(
        "Slang editor support configured. Add `import shader_studio;` to a Slang file.",
      );
    } catch (error) {
      this.configured = false;
      this.logger.error(`Failed to configure Slang focus context: ${String(error)}`);
      await vscode.window.showErrorMessage(
        `Failed to configure Slang focus context: ${String(error)}`,
      );
    }
  }

  private isIntegrationEnabled(): boolean {
    return vscode.workspace.getConfiguration("shader-studio").get<boolean>(
      "slangEditorIntegration",
      true,
    );
  }

  private disable(): void {
    if (this.focusTimer) {
      clearTimeout(this.focusTimer);
      this.focusTimer = undefined;
    }
    this.focusedDocument = undefined;
    this.configured = false;
    this.logger.info("Slang editor context integration disabled by settings.");
  }

  private handleEditorFocus(editor: vscode.TextEditor | undefined): void {
    if (
      !this.configured
      || !isSlangDocument(editor?.document)
      || this.isGeneratedDocument(editor.document)
    ) {
      return;
    }

    this.focusedDocument = editor.document;
    this.scheduleUpdate(editor.document);
  }

  private handleContextDocumentChange(event: vscode.TextDocumentChangeEvent): void {
    if (
      !this.configured
      || event.contentChanges.length === 0
      || this.isGeneratedDocument(event.document)
      || !isContextSourceDocument(event.document)
      || !this.focusedDocument
    ) {
      return;
    }

    this.scheduleUpdate(this.focusedDocument);
  }

  private scheduleUpdate(document: vscode.TextDocument): void {
    if (this.focusTimer) {
      clearTimeout(this.focusTimer);
    }
    this.focusTimer = setTimeout(() => {
      this.focusTimer = undefined;
      void this.updateGeneratedModule(document).catch((error) => {
        this.logger.error(`Failed to update Slang focus context: ${String(error)}`);
      });
    }, this.debounceMs);
  }

  private async updateGeneratedModule(focusedDocument: vscode.TextDocument): Promise<void> {
    const document = this.generatedDocument;
    if (!document) {
      return;
    }

    const source = await this.sourceProvider.buildSource(focusedDocument);
    if (source === this.lastGeneratedSource) {
      return;
    }

    const edit = new vscode.WorkspaceEdit();
    edit.replace(
      document.uri,
      new vscode.Range(
        document.positionAt(0),
        document.positionAt(document.getText().length),
      ),
      source,
    );
    const applied = await vscode.workspace.applyEdit(edit);
    if (!applied) {
      this.logger.warn("VS Code rejected the Slang focus context edit.");
      return;
    }

    this.lastGeneratedSource = source;
    await document.save();
  }

  private isGeneratedDocument(document: vscode.TextDocument): boolean {
    return this.generatedUri?.toString() === document.uri.toString();
  }
}

function isSlangDocument(
  document: vscode.TextDocument | undefined,
): document is vscode.TextDocument {
  if (!document || document.uri.scheme !== "file") {
    return false;
  }

  return document.languageId === "slang" || document.fileName.toLowerCase().endsWith(".slang");
}

function isContextSourceDocument(document: vscode.TextDocument): boolean {
  const lowerFileName = document.fileName.toLowerCase();
  return lowerFileName.endsWith(".sha.json")
    || lowerFileName.endsWith(".ts")
    || lowerFileName.endsWith(".js");
}
