import * as path from "path";

export type SlangEditorChannelKind =
  | "texture"
  | "video"
  | "cubemap"
  | "audio"
  | "buffer"
  | "keyboard";

export interface SlangEditorChannel {
  slot: number;
  key: string;
  kind: SlangEditorChannelKind;
}

export interface SlangEditorUniform {
  name: string;
  type: string;
}

export interface SlangEditorContext {
  focusedFileName: string;
  channels: SlangEditorChannel[];
  customUniforms: SlangEditorUniform[];
}

const CUSTOM_TYPES: Record<string, { type: string; initialValue: string }> = {
  float: { type: "float", initialValue: "0.0" },
  vec2: { type: "float2", initialValue: "float2(0.0)" },
  vec3: { type: "float3", initialValue: "float3(0.0)" },
  vec4: { type: "float4", initialValue: "float4(0.0)" },
  bool: { type: "bool", initialValue: "false" },
};

const BUILTIN_DECLARATIONS = `public static const float3 iResolution = float3(0.0);
public static const float4 iMouse = float4(0.0);
public static const float iTime = 0.0;
public static const float iTimeDelta = 0.0;
public static const float iFrameRate = 0.0;
public static const int iFrame = 0;
public static const float4 iChannelTime = float4(0.0);
public static const float4 iChannelLoaded = float4(0.0);
public static const float iSampleRate = 0.0;
public static const float4 iDate = float4(0.0);
public static const float3 iChannelResolution[4] = {
    float3(0.0), float3(0.0), float3(0.0), float3(0.0)
};
public static const float3 iCameraPos = float3(0.0);
public static const float3 iCameraDir = float3(0.0);`;

const CHANNEL_TYPES = `public struct ShaderStudioSampler2D
{
    float4 Sample(float2 uv) { return float4(0.0); }
};

public struct ShaderStudioSamplerCube
{
    float4 Sample(float3 dir) { return float4(0.0); }
};

public struct ShaderStudioChannel2D
{
    ShaderStudioSampler2D sampler;
    float3 size;
    float time;
    int loaded;
};

public struct ShaderStudioChannelCube
{
    ShaderStudioSamplerCube sampler;
    float3 size;
    float time;
    int loaded;
};`;

export function buildSlangEditorContextModule(context: SlangEditorContext): string {
  const channels = uniqueChannels(context.channels);
  const channelDeclarations = buildChannelDeclarations(channels);
  const uniformDeclarations = buildUniformDeclarations(context.customUniforms);
  const baseName = path.basename(
    context.focusedFileName,
    path.extname(context.focusedFileName),
  );
  const focusIdentifier = sanitizeIdentifier(baseName || "shader");

  return [
    "// Generated by Shader Studio. Do not edit.",
    "#language slang 2026",
    "module shader_studio;",
    "",
    BUILTIN_DECLARATIONS,
    "",
    CHANNEL_TYPES,
    channelDeclarations ? `\n${channelDeclarations}` : "",
    uniformDeclarations ? `\n${uniformDeclarations}` : "",
    "",
    `public static const float shaderStudioFocus_${focusIdentifier} = 1.0;`,
    "",
  ].join("\n");
}

function uniqueChannels(channels: readonly SlangEditorChannel[]): SlangEditorChannel[] {
  return Array.from(new Map(
    channels
      .filter(({ slot, key }) => Number.isInteger(slot) && slot >= 0 && isIdentifier(key))
      .map((channel) => [`${channel.slot}\0${channel.key}\0${channel.kind}`, channel]),
  ).values()).sort((left, right) => (
    left.slot - right.slot
    || left.key.localeCompare(right.key)
    || left.kind.localeCompare(right.kind)
  ));
}

function buildChannelDeclarations(channels: readonly SlangEditorChannel[]): string {
  const declarations: string[] = [];
  const signaturesBySlot = new Map<number, Set<"2d" | "cube">>();
  const signaturesByKey = new Map<string, Set<"2d" | "cube">>();

  for (const channel of channels) {
    const signature = channel.kind === "cubemap" ? "cube" : "2d";
    const signatures = signaturesByKey.get(channel.key) ?? new Set<"2d" | "cube">();
    signatures.add(signature);
    signaturesByKey.set(channel.key, signatures);
  }

  for (const channel of channels) {
    const signature = channel.kind === "cubemap" ? "cube" : "2d";
    const signatures = signaturesBySlot.get(channel.slot) ?? new Set<"2d" | "cube">();
    signatures.add(signature);
    signaturesBySlot.set(channel.slot, signatures);

    if (signaturesByKey.get(channel.key)?.size === 1) {
      const textureType = signature === "cube" ? "TextureCube<float4>" : "Texture2D<float4>";
      declarations.push(`public ${textureType} ${channel.key};`);
      declarations.push(`public SamplerState ${channel.key}Sampler;`);
    }

    if (channel.key !== `iChannel${channel.slot}`) {
      const suffix = `${channel.key[0].toUpperCase()}${channel.key.slice(1)}`;
      declarations.push(buildSampleFunction(`sample${suffix}`, signature));
    }
  }

  for (let slot = 0; slot < 4; slot += 1) {
    if (!signaturesBySlot.has(slot)) {
      signaturesBySlot.set(slot, new Set(["2d"]));
    }
  }

  for (const [slot, signatures] of [...signaturesBySlot.entries()].sort((a, b) => a[0] - b[0])) {
    for (const signature of [...signatures].sort()) {
      declarations.push(buildSampleFunction(`sampleIChannel${slot}`, signature));
    }
    if (
      slot < 4
      && signatures.size === 1
      && channels.some((channel) => channel.slot === slot)
    ) {
      const channelType = signatures.has("2d") ? "ShaderStudioChannel2D" : "ShaderStudioChannelCube";
      declarations.push(`public static ${channelType} iCh${slot};`);
    }
  }

  return Array.from(new Set(declarations)).join("\n\n");
}

function buildSampleFunction(name: string, signature: "2d" | "cube"): string {
  const parameter = signature === "cube" ? "float3 dir" : "float2 uv";
  return `public float4 ${name}(${parameter}) { return float4(0.0); }`;
}

function buildUniformDeclarations(uniforms: readonly SlangEditorUniform[]): string {
  const declarations = new Map<string, string>();
  for (const uniform of uniforms) {
    const type = CUSTOM_TYPES[uniform.type];
    if (!type || !isIdentifier(uniform.name) || declarations.has(uniform.name)) {
      continue;
    }
    declarations.set(
      uniform.name,
      `public static const ${type.type} ${uniform.name} = ${type.initialValue};`,
    );
  }
  return [...declarations.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([, declaration]) => declaration)
    .join("\n");
}

function isIdentifier(value: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(value);
}

function sanitizeIdentifier(value: string): string {
  const sanitized = value.replace(/[^A-Za-z0-9_]/g, "_");
  if (!sanitized) {
    return "shader";
  }
  return /^[0-9]/.test(sanitized) ? `_${sanitized}` : sanitized;
}
