import * as path from 'node:path';
import {
  buildGlslCompatibilityUniformDeclarationLines,
  GLSL_STABLE_DECLARATION_LINES,
  GLSL_STABLE_NAMES,
  resolveGlslInputBindings,
} from '@shader-studio/types';
import type { GlslInputLike } from '@shader-studio/types';

export interface WebglGlslInjectionSnapshot {
  shaderPath: string;
  configPath: string | null;
  passName: string;
  inputs?: Readonly<Record<string, GlslInputLike>>;
  customUniformDeclarations?: string;
}

export type WebglGlslInjectionPreparation =
  | { kind: 'valid'; snapshot: WebglGlslInjectionSnapshot }
  | { kind: 'invalid'; shaderPath: string };

export interface WebglGlslInjectionBuildResult {
  lines: string[];
  warnings: string[];
}

const GENERATED_MARKER = '// Generated by Shader Studio; do not edit.';
const CUSTOM_UNIFORM_PATTERN = /^\s*uniform\s+(float|vec2|vec3|vec4|bool)\s+([A-Za-z_]\w*)\s*;\s*$/;

function sanitizeMetadata(value: string): string {
  return value.replace(/[\r\n]+/g, ' ').replace(/\*\//g, '').trim();
}

function customUniformLines(
  declarations: string | undefined,
  ownedNames: Set<string>,
  warnings: string[],
): string[] {
  if (!declarations) {
    return [];
  }
  const lines: string[] = [];
  for (const declaration of declarations.split(/\r?\n|\r/)) {
    if (!declaration.trim()) {
      continue;
    }
    const match = declaration.match(CUSTOM_UNIFORM_PATTERN);
    if (!match) {
      warnings.push(`Invalid custom uniform declaration omitted: ${declaration.trim()}`);
      continue;
    }
    const [, type, name] = match;
    if (ownedNames.has(name)) {
      warnings.push(`Custom uniform "${name}" conflicts with an existing GLSL name and was omitted.`);
      continue;
    }
    ownedNames.add(name);
    lines.push(`uniform ${type} ${name};`);
  }
  return lines;
}

export function isManagedWebglGlslInjection(value: unknown): value is string[] {
  return Array.isArray(value) && value[0] === GENERATED_MARKER;
}

export function buildWebglGlslInjection(
  snapshot: WebglGlslInjectionSnapshot,
): WebglGlslInjectionBuildResult {
  const warnings: string[] = [];
  const bindings = resolveGlslInputBindings(snapshot.inputs);
  const channelCount = Math.max(4, bindings.length);
  const slotTypes = Array.from({ length: channelCount }, (_, slot) => (
    bindings[slot]?.samplerType ?? 'sampler2D'
  ));
  const ownedNames = new Set<string>([
    ...GLSL_STABLE_NAMES, 'iChannelResolution', 'iCh0', 'iCh1', 'iCh2', 'iCh3',
    ...Array.from({ length: channelCount }, (_, slot) => `iChannel${slot}`),
  ]);
  const aliases: string[] = [];
  for (const binding of bindings) {
    if (!binding.isCustomName) {
      continue;
    }
    if (ownedNames.has(binding.key)) {
      warnings.push(`Input alias "${binding.key}" conflicts with an existing GLSL name and was omitted.`);
      continue;
    }
    ownedNames.add(binding.key);
    aliases.push(`uniform ${binding.samplerType} ${binding.key};`);
  }
  const lines = [
    GENERATED_MARKER,
    '#version 300 es',
    `// Active shader: ${sanitizeMetadata(path.basename(snapshot.shaderPath))}`,
    `// Config: ${snapshot.configPath === null ? 'none' : sanitizeMetadata(path.basename(snapshot.configPath))}`,
    `// Pass: ${sanitizeMetadata(snapshot.passName)}`,
    ...GLSL_STABLE_DECLARATION_LINES,
    ...slotTypes.map((samplerType, slot) => `uniform ${samplerType} iChannel${slot};`),
    ...aliases,
    `uniform vec3 iChannelResolution[${channelCount}];`,
    ...buildGlslCompatibilityUniformDeclarationLines(slotTypes),
    'void mainImage(out vec4 fragColor, in vec2 fragCoord);',
    'void main() { mainImage(fragColor, gl_FragCoord.xy); }',
  ];
  const customLines = customUniformLines(snapshot.customUniformDeclarations, ownedNames, warnings);
  return { lines: customLines.length > 0 ? [...lines, ...customLines] : lines, warnings };
}
