import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

const HEADER = '// Auto-generated by Shader Studio. Do not edit.\n\n';

/**
 * Write the workspace `.vscode/shader-studio.d.ts` type definitions file.
 *
 * @param extensionPath - Path to the installed extension (used to locate the source asset).
 * @param createIfMissing - When `true`, create the file even if it doesn't exist yet (used
 *   when the user creates or selects a `.ts` script). When `false`, only update an existing
 *   file if the extension's source asset is newer (used on extension launch).
 */
export function writeWorkspaceTypeDefs(extensionPath: string, createIfMissing: boolean): void {
  const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
  if (!workspaceFolder) return;

  try {
    const sourcePath = path.join(extensionPath, 'assets', 'shader-studio-script.d.ts');
    if (!fs.existsSync(sourcePath)) return;

    const vscodeDir = path.join(workspaceFolder.uri.fsPath, '.vscode');
    const destPath = path.join(vscodeDir, 'shader-studio.d.ts');

    // On launch: skip entirely when the file doesn't already exist
    if (!createIfMissing && !fs.existsSync(destPath)) return;

    // Skip when dest already exists and is newer than (or equal to) the source asset
    if (fs.existsSync(destPath)) {
      const sourceMtime = fs.statSync(sourcePath).mtimeMs;
      const destMtime = fs.statSync(destPath).mtimeMs;
      if (sourceMtime <= destMtime) return;
    }

    const sourceContent = fs.readFileSync(sourcePath, 'utf-8');
    const fullContent = HEADER + sourceContent;

    if (!fs.existsSync(vscodeDir)) {
      fs.mkdirSync(vscodeDir, { recursive: true });
    }

    fs.writeFileSync(destPath, fullContent, 'utf-8');
  } catch {
    // Silently ignore — type-def update is best-effort
  }
}
