import { createHash } from 'node:crypto';
import { readdir } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { Plugin } from 'vite';

export interface PwaBuildIdentity {
  buildId: string;
  channel: string;
}

async function publicFiles(directory: string, root = directory): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async (entry) => entry.isDirectory()
    ? publicFiles(join(directory, entry.name), root)
    : [relative(root, join(directory, entry.name)).replaceAll('\\', '/')],
  ));
  return nested.flat();
}

/** Slang/WGSL compilers and language-service workers are sizable and optional
 * for a GLSL-only install. Their Vite file names retain these source names. */
export function isOptionalCompilerAsset(file: string): boolean {
  return /(?:slang|wgslLanguageService\.worker)/i.test(file);
}

export function serviceWorkerSource(required: string[], optional: string[], identity: PwaBuildIdentity): string {
  const cacheName = `shader-studio-${identity.channel}-${identity.buildId}`;
  const channelPrefix = `shader-studio-${identity.channel}-`;
  return `/* Generated by pwaBuildPlugin. */
const CACHE = ${JSON.stringify(cacheName)};
const CHANNEL_PREFIX = ${JSON.stringify(channelPrefix)};
const REQUIRED = ${JSON.stringify(required)};
const OPTIONAL = ${JSON.stringify(optional)};
let preparation = null;
const message = (port, data) => port?.postMessage(data);
const cacheFresh = async (cache, asset) => {
  const response = await fetch(new Request(asset, { cache: 'reload' }));
  if (!response.ok) throw new Error('Could not cache ' + asset);
  await cache.put(asset, response);
};
const installRequired = async () => {
  const cache = await caches.open(CACHE);
  for (const asset of REQUIRED) await cacheFresh(cache, asset);
  const shell = await cache.match('./', { ignoreVary: true });
  const html = shell ? await shell.clone().text() : '';
  const references = [...html.matchAll(/(?:src|href)="([^"#]+)"/g)].map((match) => match[1]);
  for (const asset of references) {
    const url = new URL(asset, self.registration.scope);
    if (url.origin === self.location.origin && !OPTIONAL.some((optional) => url.pathname.endsWith(optional))) {
      await cacheFresh(cache, url.href);
    }
  }
};
self.addEventListener('install', (event) => event.waitUntil(installRequired()));
self.addEventListener('activate', (event) => event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key.startsWith(CHANNEL_PREFIX) && key !== CACHE).map((key) => caches.delete(key)))).then(() => self.clients.claim())));
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') { self.skipWaiting(); return; }
  if (event.data?.type === 'CANCEL_PREPARE_OFFLINE') { if (preparation) preparation.cancelled = true; return; }
  if (event.data?.type !== 'PREPARE_OFFLINE') return;
  const port = event.ports[0];
  preparation = { cancelled: false };
  const task = preparation;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    let completed = 0;
    message(port, { type: 'progress', completed, total: OPTIONAL.length });
    for (const asset of OPTIONAL) {
      if (task.cancelled) { message(port, { type: 'cancelled' }); return; }
      const response = await fetch(asset);
      if (!response.ok) throw new Error('Could not cache ' + asset);
      await cache.put(asset, response);
      completed += 1;
      message(port, { type: 'progress', completed, total: OPTIONAL.length });
    }
    message(port, { type: 'complete' });
  })().catch((error) => message(port, { type: 'error', message: error instanceof Error ? error.message : String(error) })).finally(() => {
    if (preparation === task) preparation = null;
  }));
});
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(caches.match(event.request, { ignoreVary: true }).then((cached) => cached || fetch(event.request).then((response) => {
    if (response.ok && new URL(event.request.url).pathname.startsWith(self.registration.scope.replace(self.location.origin, ''))) caches.open(CACHE).then((cache) => cache.put(event.request, response.clone()));
    return response;
  }).catch(() => event.request.mode === 'navigate' ? caches.match('./', { ignoreVary: true }) : undefined)));
});`;
}

/** Emits a static, self-contained offline shell without adding a runtime PWA dependency. */
export function pwaBuildPlugin(): Plugin {
  let publicDir = '';
  let identity: PwaBuildIdentity = { buildId: 'local', channel: 'production' };
  return {
    name: 'shader-studio-pwa',
    configResolved(config) {
      publicDir = config.publicDir;
      identity = {
        buildId: config.env.VITE_BUILD_ID || process.env.VITE_BUILD_ID || process.env.GITHUB_SHA || 'local',
        channel: config.env.VITE_PREVIEW_CHANNEL || process.env.VITE_PREVIEW_CHANNEL || 'production',
      };
    },
    async generateBundle(_, bundle) {
      const files = Object.keys(bundle).filter((file) => file !== 'sw.js' && file !== 'app-build.json');
      const copiedPublic = publicDir ? await publicFiles(publicDir) : [];
      const allFiles = [...new Set(['./', ...files, ...copiedPublic])].sort();
      const required = allFiles.filter((file) => !isOptionalCompilerAsset(file));
      const optional = allFiles.filter(isOptionalCompilerAsset);
      const assetHash = createHash('sha256').update(JSON.stringify(allFiles)).digest('hex').slice(0, 12);
      const buildIdentity = { ...identity, buildId: `${identity.buildId}-${assetHash}` };
      this.emitFile({ type: 'asset', fileName: 'app-build.json', source: `${JSON.stringify(buildIdentity, null, 2)}\n` });
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: serviceWorkerSource(required, optional, buildIdentity) });
    },
  };
}
