// Generated by Shader Studio; do not edit.
// Active shader: video_audio_glsl.glsl
// Config: video_audio_glsl.sha.json
// Pass: Image

precision highp float;
out vec4 fragColor;
#define HW_PERFORMANCE 1
uniform vec3 iResolution;
uniform float iTime;
uniform float iTimeDelta;
uniform float iFrameRate;
uniform vec4 iMouse;
uniform int iFrame;
uniform vec4 iDate;
uniform float iChannelTime[4];
uniform float iSampleRate;
uniform vec3 iCameraPos;
uniform vec3 iCameraDir;

uniform sampler2D iChannel0;
uniform sampler2D iChannel1;
uniform sampler2D iChannel2;
uniform sampler2D iChannel3;
uniform vec3 iChannelResolution[4];

uniform struct {
  sampler2D sampler;
  vec3 size;
  float time;
  int loaded;
} iCh0;
uniform struct {
  sampler2D sampler;
  vec3 size;
  float time;
  int loaded;
} iCh1;
uniform struct {
  sampler2D sampler;
  vec3 size;
  float time;
  int loaded;
} iCh2;
uniform struct {
  sampler2D sampler;
  vec3 size;
  float time;
  int loaded;
} iCh3;
