// Every refusal is pinned to a fixture and a narrow diagnostic. New files and
// unexpected failures must be reviewed; a blanket catch would hide regressions.
export const supportedTraceSources = new Set([
  'wgsl/cat-head.wgsl',
  'wgsl/foundation/debugging/passes/history-source.wgsl',
  'wgsl/fullscreen-vertex.wgsl',
  'wgsl/parity/pass-timing/a.wgsl',
  'wgsl/parity/pixel-inspector/gradient.wgsl',
  'wgsl/plane.wgsl',
  'wgsl/shadertoy.wgsl',
  'wgsl/shadertoy2.wgsl',
  'wgsl/test.wgsl',
  'wgsl/vertex.wgsl',
  'wgsl/visor.wgsl',
]);

const exclusions: Array<{ diagnostic: RegExp; files: string[] }> = [
  { diagnostic: /^WGSL trace compilation failed: unresolved call target 'iChannel0Sample'$/, files: [
    'wgsl/33channels.wgsl',
    'wgsl/buffers/buffer_b.wgsl',
    'wgsl/cat-body.wgsl',
    'wgsl/compute-lab/channel-cover.wgsl',
    'wgsl/compute-lab/layered-output.wgsl',
    'wgsl/compute-lab/raw-workgroups.wgsl',
    'wgsl/compute-lab/system-values.wgsl',
    'wgsl/compute-lab/workgroup-coverage.wgsl',
    'wgsl/intellisense_compute.wgsl',
    'wgsl/keyboard.wgsl',
    'wgsl/parity/pass-timing/timing.wgsl',
    'wgsl/parity/reset-feedback/reset.wgsl',
    'wgsl/two-meshes.wgsl',
  ] },
  { diagnostic: /^Trace locals at line \d+ include an unsupported type\./, files: [
    'wgsl/backend-differences/precision/history.wgsl',
    'wgsl/backend-differences/precision/precision.wgsl',
    'wgsl/buffers/buffer_a.wgsl',
    'wgsl/compute-lab/count-dispatch.wgsl',
    'wgsl/compute-lab/dispatch-modes.wgsl',
    'wgsl/compute-lab/game-of-life.wgsl',
    'wgsl/compute-lab/multi-entry.wgsl',
    'wgsl/compute-lab/one-shot-storage.wgsl',
    'wgsl/compute-lab/repeated-substeps.wgsl',
    'wgsl/cubemap.wgsl',
    'wgsl/custom-uniforms.wgsl',
    'wgsl/feature-coverage.buffer.wgsl',
    'wgsl/feature-coverage.wgsl',
    'wgsl/flow.wgsl',
    'wgsl/foundation/debugging/debug-coverage.wgsl',
    'wgsl/foundation/debugging/passes/history.wgsl',
    'wgsl/foundation/workspace/foundation.wgsl',
    'wgsl/foundation/workspace/passes/glow.wgsl',
    'wgsl/foundation/workspace/passes/history.wgsl',
    'wgsl/gravity/gravity.wgsl',
    'wgsl/intellisense.wgsl',
    'wgsl/parity/channels/named.wgsl',
    'wgsl/parity/pass-timing/b.wgsl',
    'wgsl/parity/reset-feedback/history.wgsl',
    'wgsl/parity/resize-feedback/history.wgsl',
    'wgsl/parity/resize-feedback/resize.wgsl',
    'wgsl/particles.wgsl',
    'wgsl/structs/structs.wgsl',
    'wgsl/texture.wgsl',
    'wgsl/uniforms.wgsl',
    'wgsl/video_audio.wgsl',
    'wgsl/video.wgsl',
  ] },
  { diagnostic: /^The trace PoC requires fn mainImage\(coord: vec2f\) -> vec4f\.$/, files: [
    'wgsl/common.wgsl',
    'wgsl/feature-coverage.common.wgsl',
    'wgsl/feature-coverage.vert.wgsl',
    'wgsl/foundation/debugging/common.wgsl',
    'wgsl/foundation/workspace/common.wgsl',
    'wgsl/fullscreen-vertex.vert.wgsl',
    'wgsl/gravity/common.wgsl',
    'wgsl/intellisense.vert.wgsl',
    'wgsl/plane.vert.wgsl',
    'wgsl/structs/common.wgsl',
    'wgsl/vertex_vertex.wgsl',
    'wgsl/visor.vertex.wgsl',
  ] },
  { diagnostic: /^The trace PoC requires a mainImage shader without authored GPU bindings\/entry points/, files: [
    'wgsl/compute-lab/passes/channel-covered.wgsl',
    'wgsl/compute-lab/passes/channel-source.wgsl',
    'wgsl/compute-lab/passes/count-gradient.wgsl',
    'wgsl/compute-lab/passes/dispatch-modes-kernels.wgsl',
    'wgsl/compute-lab/passes/game-of-life.wgsl',
    'wgsl/compute-lab/passes/intellisense-compute.wgsl',
    'wgsl/compute-lab/passes/layered-output.wgsl',
    'wgsl/compute-lab/passes/multi-entry-kernels.wgsl',
    'wgsl/compute-lab/passes/one-shot-init.wgsl',
    'wgsl/compute-lab/passes/raw-workgroups.wgsl',
    'wgsl/compute-lab/passes/substep-init.wgsl',
    'wgsl/compute-lab/passes/substep.wgsl',
    'wgsl/compute-lab/passes/system-values.wgsl',
    'wgsl/compute-lab/passes/workgroup-coverage.wgsl',
    'wgsl/gravity/init.wgsl',
    'wgsl/gravity/present.wgsl',
    'wgsl/gravity/sim.wgsl',
    'wgsl/init.wgsl',
    'wgsl/present.wgsl',
    'wgsl/shadertoy2.computea.wgsl',
    'wgsl/structs/init.wgsl',
    'wgsl/structs/present.wgsl',
    'wgsl/vertex_init.wgsl',
  ] },
  { diagnostic: /^WGSL trace compilation failed: unresolved value 'colours'$/, files: [
    'wgsl/compute-lab/storage-edit-colours.wgsl',
  ] },
  { diagnostic: /^The trace PoC requires braced else blocks;/, files: [
    'wgsl/ich.wgsl',
  ] },
];

export const expectedTraceRefusals = new Map(exclusions.flatMap(group =>
  group.files.map(file => [file, group.diagnostic] as const)));
