import * as assert from 'assert';
import {
  buildShaderValidatorPreamble,
  type ShaderValidatorPreambleSnapshot,
} from '../../app/ShaderValidatorPreamble';

suite('Shader Validator preamble builder', () => {
  const build = (snapshot: Partial<ShaderValidatorPreambleSnapshot> = {}) => buildShaderValidatorPreamble({
    shaderPath: '/workspace/image.glsl',
    configPath: '/workspace/image.sha.json',
    passName: 'Image',
    ...snapshot,
  });

  function compatibilityFieldType(preamble: string, expression: string): string | null {
    const [objectName, fieldName] = expression.split('.');
    const uniformStructPattern = /uniform\s+struct\s*\{([^}]*)\}\s+([A-Za-z_]\w*)\s*;/gs;
    for (const match of preamble.matchAll(uniformStructPattern)) {
      if (match[2] !== objectName) {
        continue;
      }
      const fieldPattern = new RegExp(`\\b([A-Za-z_]\\w*)\\s+${fieldName}\\s*;`);
      return match[1].match(fieldPattern)?.[1] ?? null;
    }
    return null;
  }

  test('emits stable declarations, bindings, aliases, and valid custom uniforms', () => {
    const result = build({
      inputs: {
        albedo: { type: 'texture' },
        environment: { type: 'cubemap' },
      },
      customUniformDeclarations: [
        'uniform float exposure;',
        'uniform vec3 tint;',
      ].join('\n'),
    });

    assert.match(result.content, /Generated by Shader Studio/);
    assert.match(result.content, /Active shader: image\.glsl/);
    assert.match(result.content, /uniform sampler2D iChannel0;/);
    assert.match(result.content, /uniform samplerCube iChannel1;/);
    assert.match(result.content, /uniform sampler2D albedo;/);
    assert.match(result.content, /uniform samplerCube environment;/);
    assert.match(result.content, /uniform vec3 iChannelResolution\[4\];/);
    assert.match(result.content, /uniform float exposure;/);
    assert.match(result.content, /uniform vec3 tint;/);
    assert.deepStrictEqual(result.warnings, []);
  });

  test('defaults to four sampler2D slots without inputs', () => {
    const result = build({ configPath: null });

    for (let slot = 0; slot < 4; slot++) {
      assert.match(result.content, new RegExp(`uniform sampler2D iChannel${slot};`));
    }
    assert.match(result.content, /uniform vec3 iChannelResolution\[4\];/);
  });

  test('resizes channel resolution for five through sixteen inputs and preserves insertion order', () => {
    for (const channelCount of [5, 16]) {
      const inputs = Object.fromEntries(Array.from({ length: channelCount }, (_, slot) => [
        `input${slot}`,
        { type: slot === 4 ? 'cubemap' : 'texture' },
      ]));
      const result = build({ inputs });

      assert.match(result.content, new RegExp(`uniform vec3 iChannelResolution\\[${channelCount}\\];`));
      assert.match(result.content, /uniform samplerCube iChannel4;/);
      assert.ok(result.content.indexOf('uniform sampler2D input0;') < result.content.indexOf('uniform samplerCube input4;'));
      if (channelCount > 5) {
        assert.ok(result.content.indexOf('uniform samplerCube input4;') < result.content.indexOf(`uniform sampler2D input${channelCount - 1};`));
      }
    }
  });

  test('limits bindings to sixteen inputs', () => {
    const inputs = Object.fromEntries(Array.from({ length: 17 }, (_, slot) => [
      `input${slot}`,
      { type: 'texture' },
    ]));
    const result = build({ inputs });

    assert.match(result.content, /uniform vec3 iChannelResolution\[16\];/);
    assert.doesNotMatch(result.content, /iChannel16/);
    assert.doesNotMatch(result.content, /input16/);
  });

  test('resolves renderer-compatible field expressions through uniform struct values', () => {
    const result = build({
      inputs: {
        one: { type: 'cubemap' },
        two: { type: 'texture' },
        three: { type: 'cubemap' },
        four: { type: 'texture' },
      },
    });

    const fieldExpressions = new Map([
      ['iCh0.sampler', 'samplerCube'],
      ['iCh1.sampler', 'sampler2D'],
      ['iCh2.sampler', 'samplerCube'],
      ['iCh3.sampler', 'sampler2D'],
      ['iCh0.size', 'vec3'],
      ['iCh1.time', 'float'],
      ['iCh2.loaded', 'int'],
    ]);

    for (const [expression, expectedType] of fieldExpressions) {
      assert.strictEqual(
        compatibilityFieldType(result.content, expression),
        expectedType,
        `${expression} must resolve to a field on a generated uniform value`,
      );
    }
  });

  test('omits malformed custom declarations with warnings', () => {
    const result = build({
      customUniformDeclarations: 'uniform mat4 transform;\nfloat missingUniform;\nuniform float valid;',
    });

    assert.match(result.content, /uniform float valid;/);
    assert.doesNotMatch(result.content, /transform/);
    assert.doesNotMatch(result.content, /missingUniform/);
    assert.strictEqual(result.warnings.length, 2);
    assert.ok(result.warnings.every((warning: string) => warning.includes('Invalid custom uniform declaration')));
  });

  test('omits custom uniforms that conflict with generated names', () => {
    const result = build({
      inputs: { albedo: { type: 'texture' } },
      customUniformDeclarations: [
        'uniform float iTime;',
        'uniform float iChannel0;',
        'uniform float iCh0;',
        'uniform float albedo;',
        'uniform float iChannelResolution;',
      ].join('\n'),
    });

    assert.strictEqual(result.warnings.length, 5);
    assert.ok(result.warnings.every((warning: string) => warning.includes('conflicts')));
    assert.strictEqual((result.content.match(/uniform float iTime;/g) ?? []).length, 1);
    assert.doesNotMatch(result.content, /uniform float albedo;/);
  });

  test('omits duplicate custom uniform names after the first declaration', () => {
    const result = build({
      customUniformDeclarations: 'uniform float repeated;\nuniform vec3 repeated;',
    });

    assert.match(result.content, /uniform float repeated;/);
    assert.doesNotMatch(result.content, /uniform vec3 repeated;/);
    assert.deepStrictEqual(result.warnings, [
      'Custom uniform "repeated" conflicts with an existing GLSL name and was omitted.',
    ]);
  });

  test('omits input aliases that conflict with stable or generated slot names', () => {
    const result = build({
      inputs: {
        iChannel1: { type: 'cubemap' },
        iTime: { type: 'texture' },
        safe: { type: 'texture' },
      },
    });

    assert.match(result.content, /uniform samplerCube iChannel0;/);
    assert.match(result.content, /uniform sampler2D iChannel1;/);
    assert.match(result.content, /uniform sampler2D safe;/);
    assert.strictEqual((result.content.match(/uniform float iTime;/g) ?? []).length, 1);
    assert.strictEqual((result.content.match(/uniform sampler2D iChannel1;/g) ?? []).length, 1);
    assert.strictEqual(result.warnings.length, 2);
  });

  test('omits input aliases that conflict with channel resolution', () => {
    const result = build({
      inputs: {
        iChannelResolution: { type: 'texture' },
        safe: { type: 'texture' },
      },
    });

    assert.match(result.content, /uniform sampler2D iChannel0;/);
    assert.match(result.content, /uniform sampler2D iChannel1;/);
    assert.match(result.content, /uniform sampler2D safe;/);
    assert.doesNotMatch(result.content, /uniform sampler2D iChannelResolution;/);
    assert.deepStrictEqual(result.warnings, [
      'Input alias "iChannelResolution" conflicts with an existing GLSL name and was omitted.',
    ]);
  });

  test('omits input aliases that conflict with compatibility structs', () => {
    for (const alias of ['iCh0', 'iCh1', 'iCh2', 'iCh3']) {
      const result = build({
        inputs: {
          [alias]: { type: 'cubemap' },
          safe: { type: 'texture' },
        },
      });

      assert.doesNotMatch(result.content, new RegExp(`uniform samplerCube ${alias};`));
      assert.match(result.content, /uniform sampler2D safe;/);
      assert.deepStrictEqual(result.warnings, [
        `Input alias "${alias}" conflicts with an existing GLSL name and was omitted.`,
      ]);
    }
  });

  test('returns byte-identical output for equivalent snapshots', () => {
    const snapshot: ShaderValidatorPreambleSnapshot = {
      shaderPath: '/workspace/image.glsl',
      configPath: '/workspace/image.sha.json',
      passName: 'Image',
      inputs: { albedo: { type: 'texture' } },
      customUniformDeclarations: 'uniform float exposure;',
    };

    const first = buildShaderValidatorPreamble(snapshot);
    const second = buildShaderValidatorPreamble({ ...snapshot, inputs: { ...snapshot.inputs } });

    assert.strictEqual(first.content, second.content);
    assert.deepStrictEqual(first.warnings, second.warnings);
    assert.ok(first.content.endsWith('\n'));
    assert.ok(!first.content.endsWith('\n\n'));
  });

  test('sanitizes metadata labels so comments cannot be escaped', () => {
    const result = build({
      shaderPath: '/workspace/evil*/\nimage.glsl',
      configPath: '/workspace/config*/\r\nimage.sha.json',
      passName: 'Image*/\r\n#pragma exploit',
    });

    assert.match(result.content, /Active shader: image\.glsl/);
    assert.match(result.content, /Config: image\.sha\.json/);
    assert.match(result.content, /Pass: Image #pragma exploit/);
    assert.doesNotMatch(result.content, /\*\//);
  });
});
