import * as assert from 'assert';
import {
  buildShaderValidatorPreamble,
  type ShaderValidatorPreambleSnapshot,
} from '../../app/ShaderValidatorPreamble';

suite('Shader Validator preamble builder', () => {
  const build = (snapshot: Partial<ShaderValidatorPreambleSnapshot> = {}) => buildShaderValidatorPreamble({
    shaderPath: '/workspace/image.glsl',
    configPath: '/workspace/image.sha.json',
    passName: 'Image',
    ...snapshot,
  });

  test('emits stable declarations, bindings, aliases, and valid custom uniforms', () => {
    const result = build({
      inputs: {
        albedo: { type: 'texture' },
        environment: { type: 'cubemap' },
      },
      customUniformDeclarations: [
        'uniform float exposure;',
        'uniform vec3 tint;',
      ].join('\n'),
    });

    assert.match(result.content, /Generated by Shader Studio/);
    assert.match(result.content, /Active shader: image\.glsl/);
    assert.match(result.content, /uniform sampler2D iChannel0;/);
    assert.match(result.content, /uniform samplerCube iChannel1;/);
    assert.match(result.content, /uniform sampler2D albedo;/);
    assert.match(result.content, /uniform samplerCube environment;/);
    assert.match(result.content, /uniform vec3 iChannelResolution\[4\];/);
    assert.match(result.content, /uniform float exposure;/);
    assert.match(result.content, /uniform vec3 tint;/);
    assert.deepStrictEqual(result.warnings, []);
  });

  test('defaults to four sampler2D slots without inputs', () => {
    const result = build({ configPath: null });

    for (let slot = 0; slot < 4; slot++) {
      assert.match(result.content, new RegExp(`uniform sampler2D iChannel${slot};`));
    }
    assert.match(result.content, /uniform vec3 iChannelResolution\[4\];/);
  });

  test('uses up to sixteen input slots in insertion order', () => {
    const inputs = Object.fromEntries(Array.from({ length: 17 }, (_, slot) => [
      `input${slot}`,
      { type: slot === 4 ? 'cubemap' : 'texture' },
    ]));
    const result = build({ inputs });

    assert.match(result.content, /uniform vec3 iChannelResolution\[16\];/);
    assert.match(result.content, /uniform samplerCube iChannel4;/);
    assert.doesNotMatch(result.content, /iChannel16/);
    assert.ok(result.content.indexOf('uniform sampler2D input0;') < result.content.indexOf('uniform samplerCube input4;'));
    assert.ok(result.content.indexOf('uniform samplerCube input4;') < result.content.indexOf('uniform sampler2D input15;'));
    assert.doesNotMatch(result.content, /input16/);
  });

  test('uses the first four slot sampler types in compatibility structs', () => {
    const result = build({
      inputs: {
        one: { type: 'cubemap' },
        two: { type: 'texture' },
        three: { type: 'cubemap' },
        four: { type: 'texture' },
      },
    });

    for (const [slot, samplerType] of ['samplerCube', 'sampler2D', 'samplerCube', 'sampler2D'].entries()) {
      assert.match(result.content, new RegExp(`struct iCh${slot}\\s*\\{\\s*${samplerType} sampler;`, 's'));
    }
  });

  test('omits malformed custom declarations with warnings', () => {
    const result = build({
      customUniformDeclarations: 'uniform mat4 transform;\nfloat missingUniform;\nuniform float valid;',
    });

    assert.match(result.content, /uniform float valid;/);
    assert.doesNotMatch(result.content, /transform/);
    assert.doesNotMatch(result.content, /missingUniform/);
    assert.strictEqual(result.warnings.length, 2);
    assert.ok(result.warnings.every((warning: string) => warning.includes('Invalid custom uniform declaration')));
  });

  test('omits custom uniforms that conflict with generated names', () => {
    const result = build({
      inputs: { albedo: { type: 'texture' } },
      customUniformDeclarations: [
        'uniform float iTime;',
        'uniform float iChannel0;',
        'uniform float iCh0;',
        'uniform float albedo;',
        'uniform float iChannelResolution;',
      ].join('\n'),
    });

    assert.strictEqual(result.warnings.length, 5);
    assert.ok(result.warnings.every((warning: string) => warning.includes('conflicts')));
    assert.strictEqual((result.content.match(/uniform float iTime;/g) ?? []).length, 1);
    assert.doesNotMatch(result.content, /uniform float albedo;/);
  });

  test('omits input aliases that conflict with stable or generated slot names', () => {
    const result = build({
      inputs: {
        iChannel1: { type: 'cubemap' },
        iTime: { type: 'texture' },
        safe: { type: 'texture' },
      },
    });

    assert.match(result.content, /uniform samplerCube iChannel0;/);
    assert.match(result.content, /uniform sampler2D iChannel1;/);
    assert.match(result.content, /uniform sampler2D safe;/);
    assert.strictEqual((result.content.match(/uniform float iTime;/g) ?? []).length, 1);
    assert.strictEqual((result.content.match(/uniform sampler2D iChannel1;/g) ?? []).length, 1);
    assert.strictEqual(result.warnings.length, 2);
  });

  test('returns byte-identical output for equivalent snapshots', () => {
    const snapshot: ShaderValidatorPreambleSnapshot = {
      shaderPath: '/workspace/image.glsl',
      configPath: '/workspace/image.sha.json',
      passName: 'Image',
      inputs: { albedo: { type: 'texture' } },
      customUniformDeclarations: 'uniform float exposure;',
    };

    const first = buildShaderValidatorPreamble(snapshot);
    const second = buildShaderValidatorPreamble({ ...snapshot, inputs: { ...snapshot.inputs } });

    assert.strictEqual(first.content, second.content);
    assert.deepStrictEqual(first.warnings, second.warnings);
    assert.ok(first.content.endsWith('\n'));
    assert.ok(!first.content.endsWith('\n\n'));
  });

  test('sanitizes metadata labels so comments cannot be escaped', () => {
    const result = build({
      shaderPath: '/workspace/evil*/\nimage.glsl',
      configPath: '/workspace/config*/\r\nimage.sha.json',
      passName: 'Image*/\r\n#pragma exploit',
    });

    assert.match(result.content, /Active shader: image\.glsl/);
    assert.match(result.content, /Config: image\.sha\.json/);
    assert.match(result.content, /Pass: Image #pragma exploit/);
    assert.doesNotMatch(result.content, /\*\//);
  });
});
