import * as assert from "assert";
import * as fs from "fs";
import * as path from "path";
import * as sinon from "sinon";
import * as vscode from "vscode";
import {
  buildSlangFocusModule,
  mergeSearchPath,
  sanitizeSlangIdentifier,
  SlangFocusContextPoc,
  type SlangFocusContextSourceProvider,
  workspaceContextKey,
} from "../../app/SlangFocusContextPoc";

suite("SlangFocusContextPoc", () => {
  test("contributes the configure command to the extension manifest", () => {
    const manifestPath = path.resolve(__dirname, "../../../package.json");
    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")) as {
      contributes: { commands: Array<{ command: string; title: string }> };
    };

    assert.ok(manifest.contributes.commands.some((command) => (
      command.command === "shader-studio.configureSlangFocusContextPoc"
      && command.title === "Shader Studio: Configure Slang Editor Support"
    )));
  });

  test("sanitizes focused filenames into valid Slang identifier suffixes", () => {
    assert.strictEqual(sanitizeSlangIdentifier("buffer-a"), "buffer_a");
    assert.strictEqual(sanitizeSlangIdentifier("9 pass"), "_9_pass");
    assert.strictEqual(sanitizeSlangIdentifier(""), "shader");
  });

  test("builds deterministic generated source for the focused Slang file", () => {
    assert.strictEqual(
      buildSlangFocusModule("image.slang"),
      [
        "// Generated by Shader Studio Slang focus context PoC. Do not edit.",
        "#language slang 2026",
        "module shader_studio;",
        "",
        "public static const float shaderStudioFocus_image = 1.0;",
        "",
      ].join("\n"),
    );
  });

  test("preserves search paths and deduplicates the generated path", () => {
    const generatedPath = path.resolve("generated/slang-context");

    assert.deepStrictEqual(
      mergeSearchPath(["existing", generatedPath], generatedPath),
      ["existing", generatedPath],
    );
  });

  test("creates a stable order-independent workspace context key", () => {
    const first = { uri: vscode.Uri.file("/workspace/first") } as vscode.WorkspaceFolder;
    const second = { uri: vscode.Uri.file("/workspace/second") } as vscode.WorkspaceFolder;
    const other = { uri: vscode.Uri.file("/workspace/other") } as vscode.WorkspaceFolder;

    assert.strictEqual(
      workspaceContextKey([first, second]),
      workspaceContextKey([second, first]),
    );
    assert.notStrictEqual(
      workspaceContextKey([first, second]),
      workspaceContextKey([first, other]),
    );
    assert.match(workspaceContextKey([first, second]), /^[0-9a-f]{12}$/);
  });

  suite("service", () => {
    let sandbox: sinon.SinonSandbox;
    let commandHandler: (() => Promise<void>) | undefined;
    let editorListener: ((editor: vscode.TextEditor | undefined) => void) | undefined;
    let documentListener: ((event: vscode.TextDocumentChangeEvent) => void) | undefined;
    let configurationUpdate: sinon.SinonStub;
    let applyEdit: sinon.SinonStub;
    let saveDocument: sinon.SinonStub;
    let showErrorMessage: sinon.SinonStub;
    let officialSlangExtensionLookup: sinon.SinonStub;
    let generatedText: string;
    let context: vscode.ExtensionContext;
    let outputChannel: vscode.LogOutputChannel;
    let fileSystem: Pick<vscode.FileSystem, "createDirectory" | "writeFile">;
    let sourceProvider: SlangFocusContextSourceProvider;
    const workspaceFolder = {
      uri: vscode.Uri.file("/workspace/project"),
      name: "project",
      index: 0,
    } as vscode.WorkspaceFolder;

    function slangEditor(fileName: string): vscode.TextEditor {
      return {
        document: {
          fileName,
          languageId: "slang",
          uri: vscode.Uri.file(fileName),
        },
      } as vscode.TextEditor;
    }

    setup(() => {
      sandbox = sinon.createSandbox();
      generatedText = "";
      commandHandler = undefined;
      editorListener = undefined;
      documentListener = undefined;
      configurationUpdate = sandbox.stub().resolves();
      applyEdit = sandbox.stub(vscode.workspace, "applyEdit").resolves(true);
      saveDocument = sandbox.stub().resolves(true);

      context = {
        globalStorageUri: vscode.Uri.file("/global/storage"),
        subscriptions: [],
      } as unknown as vscode.ExtensionContext;
      outputChannel = {
        info: sandbox.stub(),
        warn: sandbox.stub(),
        error: sandbox.stub(),
      } as unknown as vscode.LogOutputChannel;

      sandbox.stub(vscode.workspace, "workspaceFolders").value([workspaceFolder]);
      sandbox.stub(vscode.window, "activeTextEditor").value(
        slangEditor("/workspace/project/image.slang"),
      );
      officialSlangExtensionLookup = sandbox.stub(vscode.extensions, "getExtension").returns(undefined);
      sandbox.stub(vscode.window, "showInformationMessage").resolves(undefined);
      showErrorMessage = sandbox.stub(vscode.window, "showErrorMessage").resolves(undefined);
      sandbox.stub(vscode.workspace, "getConfiguration").returns({
        get: sandbox.stub().returns(["/existing/slang"]),
        update: configurationUpdate,
      } as unknown as vscode.WorkspaceConfiguration);
      fileSystem = {
        createDirectory: sandbox.stub().resolves(),
        writeFile: sandbox.stub().callsFake(async (_uri, content) => {
          generatedText = Buffer.from(content).toString("utf8");
        }),
      };
      sourceProvider = {
        buildSource: sandbox.stub().callsFake(async (document: vscode.TextDocument) => (
          buildSlangFocusModule(document.fileName)
        )),
      };
      const openTextDocument = sandbox.stub(vscode.workspace, "openTextDocument") as sinon.SinonStub;
      openTextDocument.callsFake(async (uri: vscode.Uri) => ({
        uri,
        fileName: uri.fsPath,
        languageId: "slang",
        getText: () => generatedText,
        positionAt: (offset: number) => new vscode.Position(0, offset),
        save: saveDocument,
      }) as unknown as Promise<vscode.TextDocument>);
      sandbox.stub(vscode.commands, "registerCommand").callsFake((command, callback) => {
        if (command === "shader-studio.configureSlangFocusContextPoc") {
          commandHandler = callback as () => Promise<void>;
        }
        return { dispose: sandbox.stub() };
      });
      sandbox.stub(vscode.window, "onDidChangeActiveTextEditor").callsFake((listener) => {
        editorListener = listener;
        return { dispose: sandbox.stub() };
      });
      sandbox.stub(vscode.workspace, "onDidChangeTextDocument").callsFake((listener) => {
        documentListener = listener;
        return { dispose: sandbox.stub() };
      });
    });

    teardown(() => {
      sandbox.restore();
    });

    function createService(): SlangFocusContextPoc {
      return new SlangFocusContextPoc(
        context,
        outputChannel,
        25,
        fileSystem,
        sourceProvider,
      );
    }

    function installOfficialSlangExtension(): void {
      officialSlangExtensionLookup.returns({} as vscode.Extension<unknown>);
    }

    test("configures the generated module directory without replacing existing search paths", async () => {
      const service = createService();
      installOfficialSlangExtension();

      assert.ok(commandHandler);
      await commandHandler();

      const generatedDirectory = path.join(
        "/global/storage/slang-focus-context",
        workspaceContextKey([workspaceFolder]),
      );
      assert.ok(configurationUpdate.calledOnceWithExactly(
        "additionalSearchPaths",
        ["/existing/slang", generatedDirectory],
        vscode.ConfigurationTarget.Workspace,
      ));
      assert.strictEqual(generatedText, buildSlangFocusModule("image.slang"));
      service.dispose();
    });

    test("automatically configures editor support when the official Slang extension is installed", async () => {
      installOfficialSlangExtension();

      const service = createService();
      await new Promise((resolve) => setImmediate(resolve));

      assert.ok(configurationUpdate.calledOnce);
      assert.strictEqual(generatedText, buildSlangFocusModule("image.slang"));
      service.dispose();
    });

    test("rewrites and saves the open module when Slang editor focus changes", async () => {
      const clock = sandbox.useFakeTimers();
      const service = createService();
      installOfficialSlangExtension();
      assert.ok(commandHandler);
      await commandHandler();
      applyEdit.resetHistory();

      assert.ok(editorListener);
      editorListener(slangEditor("/workspace/project/buffer-a.slang"));
      await clock.tickAsync(25);

      assert.ok(applyEdit.calledOnce);
      const edit = applyEdit.firstCall.args[0] as vscode.WorkspaceEdit;
      const generatedUri = vscode.Uri.file(path.join(
        "/global/storage/slang-focus-context",
        workspaceContextKey([workspaceFolder]),
        "shader-studio.slang",
      ));
      assert.strictEqual(
        edit.get(generatedUri)[0].newText,
        buildSlangFocusModule("buffer-a.slang"),
      );
      assert.ok(saveDocument.calledOnce);
      service.dispose();
    });

    test("does not rewrite the module for non-Slang editor focus", async () => {
      const clock = sandbox.useFakeTimers();
      const service = createService();
      installOfficialSlangExtension();
      assert.ok(commandHandler);
      await commandHandler();
      applyEdit.resetHistory();

      assert.ok(editorListener);
      editorListener({
        document: {
          fileName: "/workspace/project/readme.md",
          languageId: "markdown",
          uri: vscode.Uri.file("/workspace/project/readme.md"),
        },
      } as vscode.TextEditor);
      await clock.tickAsync(25);

      assert.ok(applyEdit.notCalled);
      service.dispose();
    });

    test("ignores focus on the generated editor module", async () => {
      const clock = sandbox.useFakeTimers();
      const service = createService();
      installOfficialSlangExtension();
      assert.ok(commandHandler);
      await commandHandler();
      applyEdit.resetHistory();
      (sourceProvider.buildSource as sinon.SinonStub).resetHistory();

      const generatedPath = path.join(
        "/global/storage/slang-focus-context",
        workspaceContextKey([workspaceFolder]),
        "shader-studio.slang",
      );
      assert.ok(editorListener);
      editorListener(slangEditor(generatedPath));
      await clock.tickAsync(25);

      assert.ok((sourceProvider.buildSource as sinon.SinonStub).notCalled);
      assert.ok(applyEdit.notCalled);
      service.dispose();
    });

    test("refreshes the focused shader context when config text changes", async () => {
      const clock = sandbox.useFakeTimers();
      const service = createService();
      installOfficialSlangExtension();
      assert.ok(commandHandler);
      await commandHandler();
      applyEdit.resetHistory();
      (sourceProvider.buildSource as sinon.SinonStub).resetHistory();
      (sourceProvider.buildSource as sinon.SinonStub).resolves("updated editor contract");

      assert.ok(documentListener);
      documentListener({
        document: {
          fileName: "/workspace/project/image.sha.json",
          languageId: "json",
          uri: vscode.Uri.file("/workspace/project/image.sha.json"),
        },
        contentChanges: [{}],
      } as unknown as vscode.TextDocumentChangeEvent);
      await clock.tickAsync(25);

      assert.ok((sourceProvider.buildSource as sinon.SinonStub).calledOnce);
      assert.ok(applyEdit.calledOnce);
      service.dispose();
    });

    test("stays inactive when the workspace setting update fails", async () => {
      configurationUpdate.rejects(new Error("settings are read-only"));
      const clock = sandbox.useFakeTimers();
      const service = createService();
      installOfficialSlangExtension();
      assert.ok(commandHandler);
      await commandHandler();

      assert.ok(showErrorMessage.calledOnce);
      assert.match(showErrorMessage.firstCall.args[0], /settings are read-only/);
      assert.ok(editorListener);
      editorListener(slangEditor("/workspace/project/buffer-a.slang"));
      await clock.tickAsync(25);

      assert.ok(applyEdit.notCalled);
      service.dispose();
    });

    test("does not save when VS Code rejects the generated module edit", async () => {
      const clock = sandbox.useFakeTimers();
      applyEdit.resolves(false);
      const service = createService();
      installOfficialSlangExtension();
      assert.ok(commandHandler);
      await commandHandler();

      assert.ok(editorListener);
      editorListener(slangEditor("/workspace/project/buffer-a.slang"));
      await clock.tickAsync(25);

      assert.ok(applyEdit.calledOnce);
      assert.ok(saveDocument.notCalled);
      assert.ok((outputChannel.warn as sinon.SinonStub).calledOnce);
      service.dispose();
    });

    test("offers the official extension search when Slang is not installed", async () => {
      sandbox.restore();
      sandbox = sinon.createSandbox();
      const showInformationMessage = sandbox
        .stub(vscode.window, "showInformationMessage")
        .resolves("Open Extension" as never);
      const executeCommand = sandbox.stub(vscode.commands, "executeCommand").resolves();
      sandbox.stub(vscode.extensions, "getExtension").returns(undefined);
      sandbox.stub(vscode.commands, "registerCommand").callsFake((_command, callback) => {
        commandHandler = callback as () => Promise<void>;
        return { dispose: sandbox.stub() };
      });
      sandbox.stub(vscode.window, "onDidChangeActiveTextEditor").returns({
        dispose: sandbox.stub(),
      });
      sandbox.stub(vscode.workspace, "onDidChangeTextDocument").returns({
        dispose: sandbox.stub(),
      });

      const service = createService();
      assert.ok(commandHandler);
      await commandHandler();

      assert.ok(showInformationMessage.calledOnce);
      assert.ok(executeCommand.calledOnceWithExactly(
        "workbench.extensions.search",
        "@id:shader-slang.slang-language-extension",
      ));
      service.dispose();
    });
  });
});
