import * as assert from 'assert';
import {
  buildWebglGlslInjection,
  isManagedWebglGlslInjection,
} from '../../app/WebglGlslInjection';

suite('WebGL GLSL Editor injection builder', () => {
  test('creates a managed WebGL 2 source with Shader Studio uniforms', () => {
    const result = buildWebglGlslInjection({
      shaderPath: '/workspace/image.glsl',
      configPath: '/workspace/image.sha.json',
      passName: 'Image',
      inputs: { environment: { type: 'cubemap' } },
      customUniformDeclarations: 'uniform float exposure;',
    });

    assert.strictEqual(result.lines[0], '// Generated by Shader Studio; do not edit.');
    assert.strictEqual(result.lines[1], '#version 300 es');
    assert.ok(result.lines.includes('uniform vec3 iResolution;'));
    assert.ok(result.lines.includes('uniform samplerCube iChannel0;'));
    assert.ok(result.lines.includes('uniform samplerCube environment;'));
    assert.ok(result.lines.includes('uniform float exposure;'));
    assert.ok(isManagedWebglGlslInjection(result.lines));
  });

  test('omits conflicting and malformed custom uniforms', () => {
    const result = buildWebglGlslInjection({
      shaderPath: '/workspace/image.glsl',
      configPath: null,
      passName: 'Image',
      customUniformDeclarations: 'uniform float iTime;\nuniform mat4 invalid;\nuniform vec2 valid;',
    });

    assert.ok(result.lines.includes('uniform vec2 valid;'));
    assert.strictEqual(result.lines.filter((line) => line === 'uniform float iTime;').length, 1);
    assert.strictEqual(result.warnings.length, 2);
  });
});
