import * as assert from 'assert';
import * as sinon from 'sinon';
import * as vscode from 'vscode';
import {
  WEBGL_GLSL_EDITOR_EXTENSION_ID,
  WEBGL_GLSL_EDITOR_INJECTION_ENABLED_SETTING,
  WEBGL_GLSL_EDITOR_INJECTION_SOURCE_SETTING,
  WebglGlslEditorManager,
} from '../../app/WebglGlslEditorManager';

suite('WebGL GLSL Editor manager', () => {
  const folder = { uri: vscode.Uri.file('/workspace'), name: 'workspace', index: 0 } as vscode.WorkspaceFolder;
  let sandbox: sinon.SinonSandbox;
  let configuration: { get: sinon.SinonStub; inspect: sinon.SinonStub; update: sinon.SinonStub };

  function manager() {
    return new WebglGlslEditorManager({ subscriptions: [] } as unknown as vscode.ExtensionContext, {
      warn: sandbox.stub(), error: sandbox.stub(),
    }, {
      getExtension: sandbox.stub().returns({ id: WEBGL_GLSL_EDITOR_EXTENSION_ID }),
      getWorkspaceFolders: () => [folder],
      onDidChangeExtensions: () => ({ dispose: sandbox.stub() }),
      showInformationMessage: sandbox.stub().resolves(undefined),
    });
  }

  setup(() => {
    sandbox = sinon.createSandbox();
    configuration = {
      get: sandbox.stub().returns(undefined),
      inspect: sandbox.stub().returns({ key: 'webgl-glsl-editor.setting' }),
      update: sandbox.stub().resolves(),
    };
    sandbox.stub(vscode.workspace, 'getWorkspaceFolder').returns(folder);
    sandbox.stub(vscode.workspace, 'getConfiguration').returns(configuration as unknown as vscode.WorkspaceConfiguration);
  });

  teardown(() => sandbox.restore());

  test('installs and enables a generated injection source when WebGL GLSL Editor is installed', async () => {
    const instance = manager();
    await instance.apply({ kind: 'valid', snapshot: { shaderPath: '/workspace/image.glsl', configPath: null, passName: 'Image' } });

    sinon.assert.calledWithExactly(
      configuration.update,
      WEBGL_GLSL_EDITOR_INJECTION_SOURCE_SETTING,
      sinon.match((lines: unknown) => Array.isArray(lines) && lines.includes('uniform vec3 iResolution;')),
      vscode.ConfigurationTarget.Workspace,
    );
    sinon.assert.calledWithExactly(
      configuration.update,
      WEBGL_GLSL_EDITOR_INJECTION_ENABLED_SETTING,
      true,
      vscode.ConfigurationTarget.Workspace,
    );
  });

  test('updates a previously managed source without replacing user-owned settings', async () => {
    configuration.get.withArgs(WEBGL_GLSL_EDITOR_INJECTION_SOURCE_SETTING).returns([
      '// Generated by Shader Studio; do not edit.', '#version 300 es', 'uniform vec3 stale;',
    ]);
    const instance = manager();
    await instance.apply({ kind: 'valid', snapshot: { shaderPath: '/workspace/image.glsl', configPath: null, passName: 'Image' } });

    assert.strictEqual(configuration.update.firstCall.args[0], WEBGL_GLSL_EDITOR_INJECTION_SOURCE_SETTING);
    assert.strictEqual(configuration.update.callCount, 2);
  });

  test('disables only a managed injection when the Shader Studio integration is disabled', async () => {
    configuration.get.withArgs(WEBGL_GLSL_EDITOR_INJECTION_SOURCE_SETTING).returns([
      '// Generated by Shader Studio; do not edit.', '#version 300 es', 'uniform vec3 iResolution;',
    ]);
    const instance = new WebglGlslEditorManager(
      { subscriptions: [] } as unknown as vscode.ExtensionContext,
      { warn: sandbox.stub(), error: sandbox.stub() },
      {
        getExtension: sandbox.stub().returns({ id: WEBGL_GLSL_EDITOR_EXTENSION_ID }),
        getWorkspaceFolders: () => [folder],
        isIntegrationEnabled: () => false,
        onDidChangeExtensions: () => ({ dispose: sandbox.stub() }),
        showInformationMessage: sandbox.stub().resolves(undefined),
      },
    );

    await instance.apply({ kind: 'valid', snapshot: { shaderPath: '/workspace/image.glsl', configPath: null, passName: 'Image' } });

    sinon.assert.calledOnceWithExactly(
      configuration.update,
      WEBGL_GLSL_EDITOR_INJECTION_ENABLED_SETTING,
      false,
      vscode.ConfigurationTarget.Workspace,
    );
  });
});
