import * as assert from 'assert';
import * as vscode from 'vscode';
import * as sinon from 'sinon';
import { writeWorkspaceTypeDefs } from '../../app/WorkspaceTypeDefs';

suite('WorkspaceTypeDefs Test Suite', () => {
    const EXT_PATH = '/mock/ext';
    const SOURCE_PATH = `${EXT_PATH}/assets/shader-studio-script.d.ts`;
    const WORKSPACE_ROOT = '/mock/workspace';
    const VSCODE_DIR = `${WORKSPACE_ROOT}/.vscode`;
    const DEST_PATH = `${VSCODE_DIR}/shader-studio.d.ts`;
    const SOURCE_CONTENT = 'interface UniformContext { iTime: number; }';
    const HEADER = '// Auto-generated by Shader Studio. Do not edit.\n\n';

    let sandbox: sinon.SinonSandbox;

    function setupWorkspace() {
        sandbox.stub(vscode.workspace, 'workspaceFolders').value([
            { uri: vscode.Uri.file(WORKSPACE_ROOT), name: 'workspace', index: 0 }
        ]);
    }

    setup(() => {
        sandbox = sinon.createSandbox();
    });

    teardown(() => {
        sandbox.restore();
    });

    // ── createIfMissing = true (create/select path) ────────────────────────────

    suite('createIfMissing = true', () => {
        test('creates .d.ts when dest does not exist', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(true);
            existsStub.withArgs(DEST_PATH).returns(false);
            existsStub.withArgs(VSCODE_DIR).returns(true);
            sandbox.stub(fs, 'readFileSync').withArgs(SOURCE_PATH, 'utf-8').returns(SOURCE_CONTENT);
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, true);

            sinon.assert.calledOnce(writeStub);
            assert.strictEqual(writeStub.firstCall.args[0], DEST_PATH);
            assert.strictEqual(writeStub.firstCall.args[1], HEADER + SOURCE_CONTENT);
        });

        test('updates .d.ts when dest exists and source is newer', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(true);
            existsStub.withArgs(DEST_PATH).returns(true);
            existsStub.withArgs(VSCODE_DIR).returns(true);
            const statStub = sandbox.stub(fs, 'statSync');
            statStub.withArgs(SOURCE_PATH).returns({ mtimeMs: 3000 });
            statStub.withArgs(DEST_PATH).returns({ mtimeMs: 1000 });
            sandbox.stub(fs, 'readFileSync').withArgs(SOURCE_PATH, 'utf-8').returns(SOURCE_CONTENT);
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, true);

            sinon.assert.calledOnce(writeStub);
        });

        test('skips write when dest exists and is newer than source', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(true);
            existsStub.withArgs(DEST_PATH).returns(true);
            const statStub = sandbox.stub(fs, 'statSync');
            statStub.withArgs(SOURCE_PATH).returns({ mtimeMs: 1000 });
            statStub.withArgs(DEST_PATH).returns({ mtimeMs: 2000 });
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, true);

            sinon.assert.notCalled(writeStub);
        });

        test('creates .vscode dir when missing', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(true);
            existsStub.withArgs(DEST_PATH).returns(false);
            existsStub.withArgs(VSCODE_DIR).returns(false);
            sandbox.stub(fs, 'readFileSync').withArgs(SOURCE_PATH, 'utf-8').returns(SOURCE_CONTENT);
            sandbox.stub(fs, 'writeFileSync');
            const mkdirStub = sandbox.stub(fs, 'mkdirSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, true);

            sinon.assert.calledOnce(mkdirStub);
            assert.strictEqual(mkdirStub.firstCall.args[0], VSCODE_DIR);
        });

        test('written header contains only "Do not edit." — no replacement notice', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(true);
            existsStub.withArgs(DEST_PATH).returns(false);
            existsStub.withArgs(VSCODE_DIR).returns(true);
            sandbox.stub(fs, 'readFileSync').withArgs(SOURCE_PATH, 'utf-8').returns(SOURCE_CONTENT);
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, true);

            const written = writeStub.firstCall.args[1] as string;
            assert.ok(written.includes('Do not edit.'));
            assert.ok(!written.includes('replaced on extension updates'));
        });

        test('does nothing when no workspace folder', () => {
            const fs = require('fs');
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            // workspaceFolders not stubbed — defaults to undefined/[]
            writeWorkspaceTypeDefs(EXT_PATH, true);

            sinon.assert.notCalled(writeStub);
        });

        test('does nothing when source asset is missing', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(false);
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, true);

            sinon.assert.notCalled(writeStub);
        });
    });

    // ── createIfMissing = false (launch path) ─────────────────────────────────

    suite('createIfMissing = false', () => {
        test('updates .d.ts when dest exists and source is newer', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(true);
            existsStub.withArgs(DEST_PATH).returns(true);
            existsStub.withArgs(VSCODE_DIR).returns(true);
            const statStub = sandbox.stub(fs, 'statSync');
            statStub.withArgs(SOURCE_PATH).returns({ mtimeMs: 3000 });
            statStub.withArgs(DEST_PATH).returns({ mtimeMs: 1000 });
            sandbox.stub(fs, 'readFileSync').withArgs(SOURCE_PATH, 'utf-8').returns(SOURCE_CONTENT);
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, false);

            sinon.assert.calledOnce(writeStub);
        });

        test('skips write when dest exists and is newer than source', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(true);
            existsStub.withArgs(DEST_PATH).returns(true);
            const statStub = sandbox.stub(fs, 'statSync');
            statStub.withArgs(SOURCE_PATH).returns({ mtimeMs: 1000 });
            statStub.withArgs(DEST_PATH).returns({ mtimeMs: 2000 });
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, false);

            sinon.assert.notCalled(writeStub);
        });

        test('does nothing when dest does not exist (never auto-create on launch)', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(true);
            existsStub.withArgs(DEST_PATH).returns(false);
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, false);

            sinon.assert.notCalled(writeStub);
        });

        test('does nothing when no workspace folder', () => {
            const fs = require('fs');
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            writeWorkspaceTypeDefs(EXT_PATH, false);

            sinon.assert.notCalled(writeStub);
        });

        test('does nothing when source asset is missing', () => {
            const fs = require('fs');
            const existsStub = sandbox.stub(fs, 'existsSync');
            existsStub.withArgs(SOURCE_PATH).returns(false);
            existsStub.withArgs(DEST_PATH).returns(true);
            const writeStub = sandbox.stub(fs, 'writeFileSync');

            setupWorkspace();
            writeWorkspaceTypeDefs(EXT_PATH, false);

            sinon.assert.notCalled(writeStub);
        });
    });
});
