/// <reference types="@webgpu/types" />
import type {
  IVariableCapturer,
  CaptureCompileContext,
  CaptureCustomUniform,
  CaptureRequest,
  CaptureResult,
  CaptureUniforms,
} from "../capture/VariableCapturer";
import type { ConfigInput } from "@shader-studio/types";
import type { StorageBindingNode } from "../types/PassGraph";
import type { AsyncSlangCompiler } from "./AsyncSlangCompiler";
import type { SlangChannelBinding } from "./SlangPrelude";
import { DBG_CAPTURE_UNIFORM_SIZE, SHADERTOY_UNIFORM_SIZE } from "./SlangPrelude";
import { packShaderToyUniforms } from "./uniforms";
import { captureCounters, captureDiagTick } from "../capture/captureDiagnostics";

const SHADER_CACHE_MAX = 20;
const FLOAT_BYTES = 4;
const RGBA_CHANNELS = 4;
const ROW_ALIGNMENT = 256;

interface CachedPipeline {
  pipeline: GPURenderPipeline;
  bindGroupLayout: GPUBindGroupLayout;
  lastUsed: number;
}

interface PendingCapture {
  varName: string;
  varType: string;
  buffer: GPUBuffer;
  gridWidth: number;
  gridHeight: number;
  bytesPerRow: number;
  resolved: boolean;
  discarded: boolean;
  rgba: Float32Array | null;
}

/**
 * WebGPU/Slang implementation of the variable-capture surface. Capture
 * shaders (generated by VariableCaptureBuilder in slang dialect) are
 * compiled to WGSL once per source, then drawn once per variable with the
 * selector index in the capture uniform block. Each draw renders to an
 * rgba32float target that is copied into a mappable buffer; collectResults
 * returns the captures whose buffer mapping has resolved.
 */
export class WebGPUVariableCapturer implements IVariableCapturer {
  private pipelineCache = new Map<string, CachedPipeline>();
  private pipelineCacheOrder: string[] = [];
  private pendingCaptures: PendingCapture[] = [];
  private compileContext: CaptureCompileContext = {};
  private compileContextGeneration = 0;
  private compileContextKey: string;
  private lastError: string | null = null;
  private uniformBuffer: GPUBuffer | null = null;
  private captureUniformBuffer: GPUBuffer | null = null;
  private sampler: GPUSampler | null = null;
  private disposed = false;

  constructor(
    private readonly device: GPUDevice,
    private readonly compiler: AsyncSlangCompiler,
    compileContext: CaptureCompileContext = {},
    private readonly getChannelResources?: () => Array<{ slot: number; textureView: GPUTextureView; sampler?: GPUSampler }> | null,
    private readonly getStorageBuffers?: () => Map<string, GPUBuffer>,
  ) {
    this.compileContext = compileContext;
    this.compileContextKey = this.getDeclarationContextKey(compileContext);
  }

  setCompileContext(context: CaptureCompileContext): void {
    const nextContextKey = this.getDeclarationContextKey(context);
    if (nextContextKey !== this.compileContextKey) {
      this.compileContextGeneration++;
      this.compileContextKey = nextContextKey;
      this.pipelineCache.clear();
      this.pipelineCacheOrder = [];
    }
    this.compileContext = context;
  }

  setCustomUniforms(_declarations: string, _uniforms: CaptureCustomUniform[]): void {
    // Custom (script) uniforms are not supported by the Slang pipeline yet.
  }

  setInputBindings(_inputConfig: Record<string, ConfigInput>): void {
    // Channel views are resolved live via getChannelResources at issue time.
  }

  clearLastError(): void {
    this.lastError = null;
  }

  getLastError(): string | null {
    return this.lastError;
  }

  async issueCaptureAtPixel(
    captures: CaptureRequest[],
    pixelX: number,
    pixelY: number,
    canvasWidth: number,
    canvasHeight: number,
    uniforms: CaptureUniforms,
    shouldContinue: () => boolean = () => true,
  ): Promise<number> {
    // Convert top-left canvas coords into ShaderToy fragCoord space
    // (bottom-left origin, texel centre) — same mapping as the WebGL path.
    const captureCoord: [number, number] = [
      Math.floor(pixelX) + 0.5,
      canvasHeight - Math.floor(pixelY) - 1 + 0.5,
    ];
    return this.issue(captures, uniforms, 1, 1, captureCoord, true, canvasWidth, canvasHeight, shouldContinue);
  }

  async issueCaptureGrid(
    captures: CaptureRequest[],
    uniforms: CaptureUniforms,
    gridWidth: number,
    gridHeight: number,
    shouldContinue: () => boolean = () => true,
  ): Promise<number> {
    return this.issue(
      captures,
      uniforms,
      gridWidth,
      gridHeight,
      [0, 0],
      false,
      uniforms.res[0],
      uniforms.res[1],
      shouldContinue,
    );
  }

  collectResults(): CaptureResult[] {
    const results: CaptureResult[] = [];
    const remaining: PendingCapture[] = [];
    for (const pending of this.pendingCaptures) {
      if (pending.discarded) {
        continue;
      }
      if (pending.resolved && pending.rgba) {
        results.push({ varName: pending.varName, varType: pending.varType, rgba: pending.rgba });
      } else {
        remaining.push(pending);
      }
    }
    this.pendingCaptures = remaining;
    return results;
  }

  cancelPendingCaptures(): void {
    let destroyed = 0;
    for (const pending of this.pendingCaptures) {
      // Skip buffers already destroyed on successful readback.
      if (pending.resolved || pending.discarded) {
        continue;
      }
      pending.discarded = true;
      // destroy() is safe while a mapAsync is outstanding — it rejects the map.
      pending.buffer.destroy?.();
      captureCounters.gpuBuffersDestroyed++;
      destroyed++;
    }
    if (this.pendingCaptures.length > 0) {
      captureDiagTick("capturer.cancel", {
        cancelledPending: this.pendingCaptures.length,
        buffersDestroyedNow: destroyed,
      });
    }
    this.pendingCaptures = [];
  }

  dispose(): void {
    this.disposed = true;
    this.compileContextGeneration++;
    this.cancelPendingCaptures();
    if (this.uniformBuffer) {
      this.uniformBuffer.destroy?.(); captureCounters.gpuBuffersDestroyed++;
    }
    this.uniformBuffer = null;
    if (this.captureUniformBuffer) {
      this.captureUniformBuffer.destroy?.(); captureCounters.gpuBuffersDestroyed++;
    }
    this.captureUniformBuffer = null;
    this.pipelineCache.clear();
    this.pipelineCacheOrder = [];
  }

  private async issue(
    captures: CaptureRequest[],
    uniforms: CaptureUniforms,
    gridWidth: number,
    gridHeight: number,
    captureCoord: [number, number],
    isPixelMode: boolean,
    canvasWidth: number,
    canvasHeight: number,
    shouldContinue: () => boolean,
  ): Promise<number> {
    this.clearLastError();
    if (captures.length === 0 || this.disposed) {
      return 0;
    }

    const channels = this.compileContext.slangChannels ?? [];
    const storage = this.compileContext.slangStorage ?? [];
    const commonCode = this.compileContext.commonCode;
    const compileContextGeneration = this.compileContextGeneration;
    const compileContextKey = this.compileContextKey;
    const channelResources = channels.length > 0 ? this.getChannelResources?.() ?? null : [];
    if (channels.length > 0 && channelResources === null) {
      this.lastError = "Capture channels are not resolvable yet";
      return 0;
    }
    if (!this.resolveStorageBuffers(storage)) {
      return 0;
    }

    this.ensureUniformBuffers();
    this.device.queue.writeBuffer(
      this.uniformBuffer!,
      0,
      packShaderToyUniforms({
        width: canvasWidth,
        height: canvasHeight,
        time: uniforms.time,
        timeDelta: uniforms.timeDelta,
        frameRate: uniforms.frameRate,
        frame: uniforms.frame,
        mouse: uniforms.mouse,
      }),
    );

    const bytesPerRow = Math.ceil((gridWidth * RGBA_CHANNELS * FLOAT_BYTES) / ROW_ALIGNMENT) * ROW_ALIGNMENT;
    const target = this.device.createTexture({
      size: { width: gridWidth, height: gridHeight },
      format: "rgba32float",
      usage: (globalThis.GPUTextureUsage?.RENDER_ATTACHMENT ?? 0x10) | (globalThis.GPUTextureUsage?.COPY_SRC ?? 0x01),
    });
    captureCounters.gpuTexturesCreated++;
    const targetView = target.createView();

    let issued = 0;
    try {
      for (const capture of captures) {
        if (!shouldContinue() || this.disposed) {
          break;
        }

        const cached = await this.getOrCompilePipeline(
          capture.captureShader,
          commonCode,
          channels,
          storage,
          compileContextGeneration,
          compileContextKey,
        );
        if (
          !shouldContinue() ||
          !this.isCompileContextCurrent(compileContextGeneration, compileContextKey)
        ) {
          break;
        }
        if (!cached) {
          continue;
        }

        const storageBuffers = this.resolveStorageBuffers(storage);
        if (!storageBuffers) {
          continue;
        }
        const bindGroup = this.buildBindGroup(
          cached.bindGroupLayout,
          channelResources ?? [],
          storage,
          storageBuffers,
        );
        if (!bindGroup) {
          continue;
        }

        this.writeCaptureUniforms(captureCoord, gridWidth, gridHeight, capture.selectorIndex ?? 0, isPixelMode);

        const readbackBuffer = this.device.createBuffer({
          size: bytesPerRow * gridHeight,
          usage: (globalThis.GPUBufferUsage?.MAP_READ ?? 0x0001) | (globalThis.GPUBufferUsage?.COPY_DST ?? 0x0008),
        });
        captureCounters.gpuBuffersCreated++;

        const encoder = this.device.createCommandEncoder();
        const renderPass = encoder.beginRenderPass({
          colorAttachments: [{
            view: targetView,
            clearValue: { r: 0, g: 0, b: 0, a: 0 },
            loadOp: "clear",
            storeOp: "store",
          }],
        });
        renderPass.setPipeline(cached.pipeline);
        renderPass.setBindGroup(0, bindGroup);
        renderPass.draw(3);
        renderPass.end();
        encoder.copyTextureToBuffer(
          { texture: target },
          { buffer: readbackBuffer, bytesPerRow },
          { width: gridWidth, height: gridHeight },
        );
        this.device.queue.submit([encoder.finish()]);

        const pending: PendingCapture = {
          varName: capture.varName,
          varType: capture.varType,
          buffer: readbackBuffer,
          gridWidth,
          gridHeight,
          bytesPerRow,
          resolved: false,
          discarded: false,
          rgba: null,
        };
        this.pendingCaptures.push(pending);
        this.beginReadback(pending);
        issued++;
      }
    } finally {
      target.destroy?.();
      captureCounters.gpuTexturesDestroyed++;
    }

    captureCounters.capturesIssued += issued;
    captureDiagTick("capturer.issue", {
      pendingCaptures: this.pendingCaptures.length,
      pipelineCacheSize: this.pipelineCache.size,
      issuedThisCall: issued,
      gridW: gridWidth,
      gridH: gridHeight,
    });

    return issued;
  }

  private beginReadback(pending: PendingCapture): void {
    const MAP_READ_MODE = globalThis.GPUMapMode?.READ ?? 0x0001;
    pending.buffer.mapAsync(MAP_READ_MODE)
      .then(() => {
        if (pending.discarded) {
          return;
        }
        const mapped = new Uint8Array(pending.buffer.getMappedRange()).slice();
        pending.buffer.unmap();
        pending.buffer.destroy?.();
        captureCounters.gpuBuffersDestroyed++;
        captureCounters.readbacksResolved++;
        // Strip the 256-byte row alignment into tight rows.
        const rowFloats = pending.gridWidth * RGBA_CHANNELS;
        const rgba = new Float32Array(rowFloats * pending.gridHeight);
        const strided = new Float32Array(mapped.buffer);
        const strideFloats = pending.bytesPerRow / FLOAT_BYTES;
        for (let row = 0; row < pending.gridHeight; row++) {
          rgba.set(strided.subarray(row * strideFloats, row * strideFloats + rowFloats), row * rowFloats);
        }
        pending.rgba = rgba;
        pending.resolved = true;
      })
      .catch(() => {
        pending.discarded = true;
      });
  }

  private async getOrCompilePipeline(
    captureShader: string,
    commonCode: string | undefined,
    channels: SlangChannelBinding[],
    storage: StorageBindingNode[],
    compileContextGeneration: number,
    compileContextKey: string,
  ): Promise<CachedPipeline | null> {
    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }
    const pipelineCacheKey = JSON.stringify([compileContextKey, captureShader]);
    const existing = this.pipelineCache.get(pipelineCacheKey);
    if (existing) {
      existing.lastUsed = performance.now();
      return existing;
    }

    captureCounters.pipelineCompiles++;
    const compileResult = await this.compiler.compile(captureShader, {
      passName: "capture",
      commonCode,
      channels,
      storage,
      passKind: "render",
      captureMode: true,
    });
    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }
    if (!compileResult.success) {
      this.lastError = compileResult.errors.join("\n");
      return null;
    }

    let pipeline: GPURenderPipeline;
    let bindGroupLayout: GPUBindGroupLayout;
    try {
      const shaderModule = this.device.createShaderModule({ code: compileResult.wgsl });
      bindGroupLayout = this.device.createBindGroupLayout({
        entries: this.buildBindGroupLayoutEntries(channels, storage),
      });
      const descriptor: GPURenderPipelineDescriptor = {
        layout: this.device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] }),
        vertex: { module: shaderModule, entryPoint: "vertexMain" },
        fragment: {
          module: shaderModule,
          entryPoint: "fragmentMain",
          targets: [{ format: "rgba32float" }],
        },
        primitive: { topology: "triangle-list" },
      };
      pipeline = this.device.createRenderPipelineAsync
        ? await this.device.createRenderPipelineAsync(descriptor)
        : this.device.createRenderPipeline(descriptor);
    } catch (error) {
      if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
        return null;
      }
      this.lastError = error instanceof Error ? error.message : String(error);
      return null;
    }

    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }

    if (this.pipelineCacheOrder.length >= SHADER_CACHE_MAX) {
      const oldest = this.pipelineCacheOrder.shift()!;
      this.pipelineCache.delete(oldest);
    }
    const cached: CachedPipeline = { pipeline, bindGroupLayout, lastUsed: performance.now() };
    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }
    this.pipelineCache.set(pipelineCacheKey, cached);
    this.pipelineCacheOrder.push(pipelineCacheKey);
    return cached;
  }

  private getDeclarationContextKey(context: CaptureCompileContext): string {
    return JSON.stringify([
      context.commonCode ?? "",
      context.slangChannels ?? [],
      context.slangStorage ?? [],
    ]);
  }

  private isCompileContextCurrent(generation: number, contextKey: string): boolean {
    return !this.disposed &&
      generation === this.compileContextGeneration &&
      contextKey === this.compileContextKey;
  }

  /**
   * Layout mirrors SlangPassPipeline (binding 0 = ShaderToy uniforms, then
   * texture/sampler pairs over the slot-sorted channel array), then storage,
   * with the capture uniform block appended after every pass resource.
   */
  private buildBindGroupLayoutEntries(
    channels: SlangChannelBinding[],
    storage: StorageBindingNode[],
  ): GPUBindGroupLayoutEntry[] {
    const FRAGMENT = globalThis.GPUShaderStage?.FRAGMENT ?? 0x2;
    const VERTEX = globalThis.GPUShaderStage?.VERTEX ?? 0x1;
    const entries: GPUBindGroupLayoutEntry[] = [{
      binding: 0,
      visibility: VERTEX | FRAGMENT,
      buffer: { type: "uniform" },
    }];
    const sorted = [...channels].sort((a, b) => a.slot - b.slot);
    for (let index = 0; index < sorted.length; index++) {
      entries.push({
        binding: 1 + index * 2,
        visibility: FRAGMENT,
        texture: { sampleType: "float" },
      });
      entries.push({
        binding: 2 + index * 2,
        visibility: FRAGMENT,
        sampler: { type: "filtering" },
      });
    }
    const storageBaseBinding = 1 + sorted.length * 2;
    for (const node of storage) {
      entries.push({
        binding: storageBaseBinding + node.binding,
        visibility: FRAGMENT,
        buffer: { type: "read-only-storage" },
      });
    }
    entries.push({
      binding: storageBaseBinding + storage.length,
      visibility: FRAGMENT,
      buffer: { type: "uniform" },
    });
    return entries;
  }

  private buildBindGroup(
    layout: GPUBindGroupLayout,
    channelResources: Array<{ slot: number; textureView: GPUTextureView; sampler?: GPUSampler }>,
    storage: StorageBindingNode[],
    storageBuffers: Map<string, GPUBuffer>,
  ): GPUBindGroup | null {
    if (!this.uniformBuffer || !this.captureUniformBuffer) {
      return null;
    }
    const entries: GPUBindGroupEntry[] = [{ binding: 0, resource: { buffer: this.uniformBuffer } }];
    const sorted = [...channelResources].sort((a, b) => a.slot - b.slot);
    for (let index = 0; index < sorted.length; index++) {
      entries.push({ binding: 1 + index * 2, resource: sorted[index].textureView });
      entries.push({ binding: 2 + index * 2, resource: sorted[index].sampler ?? this.sampler! });
    }
    const storageBaseBinding = 1 + sorted.length * 2;
    for (const node of storage) {
      entries.push({
        binding: storageBaseBinding + node.binding,
        resource: { buffer: storageBuffers.get(node.name)! },
      });
    }
    entries.push({
      binding: storageBaseBinding + storage.length,
      resource: { buffer: this.captureUniformBuffer },
    });
    try {
      return this.device.createBindGroup({ layout, entries });
    } catch (error) {
      this.lastError = error instanceof Error ? error.message : String(error);
      return null;
    }
  }

  private resolveStorageBuffers(storage: StorageBindingNode[]): Map<string, GPUBuffer> | null {
    const buffers = this.getStorageBuffers?.() ??
      this.compileContext.slangStorageBuffers ??
      new Map<string, GPUBuffer>();
    const missing = storage.find((node) => !buffers.has(node.name));
    if (missing) {
      this.lastError = `Capture storage buffer "${missing.name}" is not resolvable yet`;
      return null;
    }
    return buffers;
  }

  private ensureUniformBuffers(): void {
    const UNIFORM = globalThis.GPUBufferUsage?.UNIFORM ?? 0x0040;
    const COPY_DST = globalThis.GPUBufferUsage?.COPY_DST ?? 0x0008;
    if (!this.uniformBuffer) {
      this.uniformBuffer = this.device.createBuffer({
        size: SHADERTOY_UNIFORM_SIZE,
        usage: UNIFORM | COPY_DST,
      });
      captureCounters.gpuBuffersCreated++;
    }
    if (!this.captureUniformBuffer) {
      this.captureUniformBuffer = this.device.createBuffer({
        size: DBG_CAPTURE_UNIFORM_SIZE,
        usage: UNIFORM | COPY_DST,
      });
      captureCounters.gpuBuffersCreated++;
    }
    if (!this.sampler) {
      this.sampler = this.device.createSampler({ magFilter: "linear", minFilter: "linear" });
    }
  }

  private writeCaptureUniforms(
    captureCoord: [number, number],
    gridWidth: number,
    gridHeight: number,
    varIndex: number,
    isPixelMode: boolean,
  ): void {
    const buf = new ArrayBuffer(DBG_CAPTURE_UNIFORM_SIZE);
    const f32 = new Float32Array(buf);
    const i32 = new Int32Array(buf);
    f32[0] = captureCoord[0];
    f32[1] = captureCoord[1];
    f32[2] = gridWidth;
    f32[3] = gridHeight;
    i32[4] = varIndex | 0;
    i32[5] = isPixelMode ? 1 : 0;
    this.device.queue.writeBuffer(this.captureUniformBuffer!, 0, buf);
  }
}
