/// <reference types="@webgpu/types" />
import type {
  IVariableCapturer,
  CaptureCompileContext,
  CaptureCustomUniform,
  CaptureRequest,
  CaptureResult,
  CaptureUniforms,
} from "../capture/VariableCapturer";
import type { ConfigInput, DebugInstrumentationPlan } from "@shader-studio/types";
import type { StorageBindingNode } from "../types/PassGraph";
import type { AsyncSlangCompiler } from "./AsyncSlangCompiler";
import type { SlangChannelBinding } from "./SlangPrelude";
import { DBG_CAPTURE_UNIFORM_SIZE, getShaderToyChannelCount } from "./SlangPrelude";
import { createSlangCustomUniformLayout, packShaderToyUniforms } from "./uniforms";
import { captureCounters, captureDiagTick } from "../capture/captureDiagnostics";
import { CaptureErrorLog, type CaptureError } from "../capture/CaptureErrorLog";
import { NativeRasterCaptureTarget } from "./NativeRasterCaptureTarget";
import { CaptureTargetLifecycle } from "./CaptureTargetLifecycle";
import { compileCapturePipeline, type CachedCapturePipeline } from "./CapturePipelineCache";
import { captureDeclarationContextKey } from "./CaptureDeclarationContextKey";
import { encodeVariableCapture, type CaptureSample } from "./VariableCaptureDraw";
import { createNativeMeshUniformBuffer } from "./NativeCaptureMeshBinding";
import { createStorageCaptureSnapshots, releaseStorageCaptureSnapshot, type StorageCaptureSnapshot } from "./StorageCaptureSnapshots";
import { createCaptureBindGroup } from "./CaptureBindGroup";

const SHADER_CACHE_MAX = 20;
const FLOAT_BYTES = 4;
const RGBA_CHANNELS = 4;
const ROW_ALIGNMENT = 256;

type CachedPipeline = CachedCapturePipeline;

interface PendingCapture {
  varName: string;
  varType: string;
  buffer: GPUBuffer;
  gridWidth: number;
  gridHeight: number;
  bytesPerRow: number;
  resolved: boolean;
  discarded: boolean;
  destroyed: boolean;
  rgba: Float32Array | null;
  hidden?: boolean;
}

interface CaptureIssueResources {
  channels: SlangChannelBinding[];
  storage: StorageBindingNode[];
  commonCode: string | undefined;
  generation: number;
  contextKey: string;
  rasterContext: CaptureCompileContext["nativeRender"];
  channelSnapshot: { resources: Array<{ slot: number; textureView: GPUTextureView; sampler?: GPUSampler }>; textureCount: number; destroy(): void };
  meshUniformBuffer: GPUBuffer | undefined;
  storageSnapshots: StorageCaptureSnapshot[];
}

/**
 * WebGPU/Slang implementation of the variable-capture surface. Capture
 * shaders (generated by VariableCaptureBuilder in slang dialect) are
 * compiled to WGSL once per source, then drawn once per variable with the
 * selector index in the capture uniform block. Each draw renders to an
 * rgba32float target that is copied into a mappable buffer; collectResults
 * returns the captures whose buffer mapping has resolved.
 */
export class WebGPUVariableCapturer implements IVariableCapturer {
  private pipelineCache = new Map<string, CachedPipeline>();
  private pipelineCacheOrder: string[] = [];
  private pendingCaptures: PendingCapture[] = [];
  private readonly captureTargets: CaptureTargetLifecycle;
  private compileContext: CaptureCompileContext = {};
  private compileContextGeneration = 0;
  /** Set when an issue bailed on resources that were still resolving. */
  private deferred = false;
  private compileContextKey: string;
  private readonly errors = new CaptureErrorLog();
  /**
   * Compiling and binding happen in helpers that do not know which variable
   * they were called for, so they park the message here and the issue loop
   * attributes it to the capture in flight.
   */
  private pendingError: string | null = null;
  private uniformBuffer: GPUBuffer | null = null;
  private captureUniformBuffer: GPUBuffer | null = null;
  private sampler: GPUSampler | null = null;
  private customUniforms: CaptureCustomUniform[] = [];
  private disposed = false;

  constructor(
    private readonly device: GPUDevice,
    private readonly compiler: AsyncSlangCompiler,
    compileContext: CaptureCompileContext = {},
    private readonly getChannelResources?: (
      context: CaptureCompileContext,
    ) => Array<{ slot: number; textureView: GPUTextureView; sampler?: GPUSampler }> | null,
    private readonly getStorageBuffers?: () => Map<string, GPUBuffer>,
  ) {
    this.captureTargets = new CaptureTargetLifecycle(
      device,
      (count) => captureCounters.gpuTexturesCreated += count,
      (count) => captureCounters.gpuTexturesDestroyed += count,
    );
    this.compileContext = compileContext;
    this.compileContextKey = captureDeclarationContextKey(compileContext);
  }

  setCompileContext(context: CaptureCompileContext): void {
    const nextContextKey = captureDeclarationContextKey(context);
    if (nextContextKey !== this.compileContextKey) {
      this.compileContextGeneration++;
      this.compileContextKey = nextContextKey;
      this.pipelineCache.clear();
      this.pipelineCacheOrder = [];
      this.uniformBuffer?.destroy?.();
      this.uniformBuffer = null;
    }
    this.compileContext = context;
  }

  setCustomUniforms(_declarations: string, uniforms: CaptureCustomUniform[]): void {
    const previousShape = JSON.stringify(this.customUniforms.map(({ name, type }) => ({ name, type })));
    const nextShape = JSON.stringify(uniforms.map(({ name, type }) => ({ name, type })));
    this.customUniforms = uniforms.map((uniform) => ({
      ...uniform,
      value: Array.isArray(uniform.value) ? [...uniform.value] : uniform.value,
    }));
    if (previousShape !== nextShape) {
      this.pipelineCache.clear();
      this.pipelineCacheOrder = [];
      this.uniformBuffer?.destroy?.();
      this.uniformBuffer = null;
    }
  }

  setInputBindings(_inputConfig: Record<string, ConfigInput>): void {
    // Channel views are resolved live via getChannelResources at issue time.
  }

  clearLastError(): void {
    this.errors.clear();
    this.pendingError = null;
    this.deferred = false;
  }

  /**
   * Channel views, storage buffers and the compile context are all resolved
   * live, so a batch can issue nothing simply because a pass rebuild has not
   * settled. That is not a capture failure - the caller retries it.
   */
  issueDeferred(): boolean {
    return this.deferred;
  }

  /** Files whatever a helper parked against the variable it failed for. */
  private recordPendingError(varName?: string): void {
    this.errors.record(this.pendingError, varName);
    this.pendingError = null;
  }
  getLastError(): string | null {
    return this.errors.lastMessage;
  }
  getCaptureErrors(): readonly CaptureError[] {
    return this.errors.list();
  }

  async issueCaptureAtPixel(
    captures: CaptureRequest[],
    pixelX: number,
    pixelY: number,
    canvasWidth: number,
    canvasHeight: number,
    uniforms: CaptureUniforms,
    shouldContinue: () => boolean = () => true,
  ): Promise<number> {
    // Convert top-left canvas coords into ShaderToy fragCoord space
    // (bottom-left origin, texel centre) — same mapping as the WebGL path.
    const captureCoord: [number, number] = [
      Math.floor(pixelX) + 0.5,
      canvasHeight - Math.floor(pixelY) - 1 + 0.5,
    ];
    return this.issue(captures, uniforms, 1, 1, captureCoord, true, canvasWidth, canvasHeight, shouldContinue);
  }

  async issueCaptureGrid(
    captures: CaptureRequest[],
    uniforms: CaptureUniforms,
    gridWidth: number,
    gridHeight: number,
    shouldContinue: () => boolean = () => true,
  ): Promise<number> {
    return this.issue(
      captures,
      uniforms,
      gridWidth,
      gridHeight,
      [0, 0],
      false,
      uniforms.res[0],
      uniforms.res[1],
      shouldContinue,
    );
  }

  collectResults(): CaptureResult[] {
    const results: CaptureResult[] = [];
    const remaining: PendingCapture[] = [];
    for (const pending of this.pendingCaptures) {
      if (pending.discarded) {
        continue;
      }
      if (pending.resolved && pending.rgba) {
        results.push({ varName: pending.varName, varType: pending.varType, rgba: pending.rgba, hidden: pending.hidden });
      } else {
        remaining.push(pending);
      }
    }
    this.pendingCaptures = remaining;
    return results;
  }

  cancelPendingCaptures(): void {
    for (const pending of this.pendingCaptures) {
      if (pending.resolved || pending.discarded) {
        continue;
      }
      pending.discarded = true;
    }
    if (this.pendingCaptures.length > 0) {
      captureDiagTick("capturer.cancel", {
        cancelledPending: this.pendingCaptures.length,
        buffersDestroyedNow: 0,
      });
    }
    this.pendingCaptures = [];
  }

  dispose(): void {
    this.disposed = true;
    this.compileContextGeneration++;
    this.cancelPendingCaptures();
    if (this.uniformBuffer) {
      this.uniformBuffer.destroy?.(); captureCounters.gpuBuffersDestroyed++;
    }
    this.uniformBuffer = null;
    if (this.captureUniformBuffer) {
      this.captureUniformBuffer.destroy?.(); captureCounters.gpuBuffersDestroyed++;
    }
    this.captureUniformBuffer = null;
    this.pipelineCache.clear();
    this.pipelineCacheOrder = [];
    this.captureTargets.dispose();
  }

  private async issue(
    captures: CaptureRequest[],
    uniforms: CaptureUniforms,
    gridWidth: number,
    gridHeight: number,
    captureCoord: [number, number],
    isPixelMode: boolean,
    canvasWidth: number,
    canvasHeight: number,
    shouldContinue: () => boolean,
  ): Promise<number> {
    this.clearLastError();
    if (captures.length === 0 || this.disposed) {
      return 0;
    }
    if (!this.validateCaptureBatch(captures)) {
      return 0;
    }
    const resources = this.prepareCaptureResources(captures);
    if (!resources) {
      return 0;
    }
    return this.issuePreparedCaptures(resources, captures, uniforms, shouldContinue, {
      gridWidth, gridHeight, captureCoord, isPixelMode, canvasWidth, canvasHeight,
    });
  }

  private prepareCaptureResources(captures: CaptureRequest[]): CaptureIssueResources | null {
    const hasNativeHookVertex = Boolean(
      this.compileContext.nativeRender?.vertexEntryPoint && !this.compileContext.nativeRender.fragmentEntryPoint,
    );
    const rasterContext = captures[0]?.debugPlan?.nativeRender || hasNativeHookVertex
      ? this.compileContext.nativeRender
      : undefined;

    const channels = this.compileContext.slangChannels ?? [];
    const storage = this.compileContext.slangStorage ?? [];
    const generation = this.compileContextGeneration;
    const contextKey = this.compileContextKey;
    const channelSnapshot = this.captureChannelSnapshot(channels);
    if (!channelSnapshot || !this.captureResourcesReady(storage)) {
      if (channelSnapshot) {
        this.releaseChannelSnapshot(channelSnapshot);
      }
      return null;
    }

    const meshUniformBuffer = this.createMeshUniformSnapshot(rasterContext);
    if (rasterContext && rasterContext.geometry !== "fullscreen" && !meshUniformBuffer) {
      this.errors.record("Native mesh capture requires a frozen mesh uniform snapshot.");
      this.releaseChannelSnapshot(channelSnapshot);
      return null;
    }

    try {
      const sourceStorage = this.resolveStorageBuffers(storage);
      if (!sourceStorage) {
        this.recordPendingError();
        this.deferred = true;
        this.releaseIssueResources(channelSnapshot, meshUniformBuffer, []);
        return null;
      }
      const storageSnapshots = createStorageCaptureSnapshots(
        this.device, captures.length, storage, sourceStorage,
        () => {
          captureCounters.gpuBuffersCreated++;
        },
        () => {
          captureCounters.gpuBuffersDestroyed++;
        },
      );
      return {
        channels, storage, commonCode: this.compileContext.commonCode, generation, contextKey, rasterContext,
        channelSnapshot, meshUniformBuffer, storageSnapshots,
      };
    } catch (error) {
      this.errors.record(error instanceof Error ? error.message : String(error));
      this.releaseIssueResources(channelSnapshot, meshUniformBuffer, []);
      return null;
    }
  }

  private async issuePreparedCaptures(
    resources: CaptureIssueResources,
    captures: CaptureRequest[],
    uniforms: CaptureUniforms,
    shouldContinue: () => boolean,
    sample: Omit<CaptureSample, "bytesPerRow">,
  ): Promise<number> {
    const { channels, storage, commonCode, generation, contextKey, rasterContext, channelSnapshot, meshUniformBuffer, storageSnapshots } = resources;
    this.writeFrameUniforms(channels, uniforms, rasterContext?.width ?? sample.canvasWidth, rasterContext?.height ?? sample.canvasHeight);
    const bytesPerRow = Math.ceil((sample.gridWidth * RGBA_CHANNELS * FLOAT_BYTES) / ROW_ALIGNMENT) * ROW_ALIGNMENT;
    const readbackOutput = captures[0]?.debugPlan?.nativeRender?.output ?? 0;
    let issued = 0;
    let target: GPUTexture | undefined;
    let targetView: GPUTextureView | undefined;
    let nativeTarget: NativeRasterCaptureTarget | undefined;
    try {
      const created = this.captureTargets.create(rasterContext, sample.gridWidth, sample.gridHeight, readbackOutput);
      nativeTarget = created.native;
      target = created.texture;
      targetView = created.view;
      if (!target || !targetView) {
        return 0;
      }
      for (const [captureIndex, capture] of captures.entries()) {
        if (!shouldContinue() || this.disposed) {
          break;
        }

        const cached = await this.resolveCapturePipeline(capture, commonCode, channels, storage, generation, contextKey, shouldContinue);
        if (cached === undefined) {
          break;
        }
        if (cached === null) {
          continue;
        }

        const bindGroup = this.resolveCaptureBindGroup(
          cached.bindGroupLayout, channels, channelSnapshot.resources, storage, storageSnapshots[captureIndex]!.buffers, capture.varName, meshUniformBuffer,
          Boolean(rasterContext),
        );
        if (!bindGroup) {
          continue;
        }

        issued += this.submitCapture(capture, cached.pipeline, bindGroup, target, targetView,
          { ...sample, bytesPerRow }, nativeTarget, rasterContext);

      }
    } catch (error) {
      this.errors.record(error instanceof Error ? error.message : String(error));
    } finally {
      if (target) {
        this.captureTargets.release(target, nativeTarget, issued > 0);
      }
      this.releaseIssueResources(channelSnapshot, meshUniformBuffer, storageSnapshots, issued > 0);
    }

    captureCounters.capturesIssued += issued;
    captureDiagTick("capturer.issue", {
      pendingCaptures: this.pendingCaptures.length,
      pipelineCacheSize: this.pipelineCache.size,
      issuedThisCall: issued,
      gridW: sample.gridWidth,
      gridH: sample.gridHeight,
    });

    return issued;
  }

  private releaseIssueResources(
    channelSnapshot: CaptureIssueResources["channelSnapshot"], meshUniformBuffer: GPUBuffer | undefined,
    storageSnapshots: StorageCaptureSnapshot[], submitted = false,
  ): void {
    this.releaseMeshUniformSnapshot(meshUniformBuffer, submitted);
    for (const snapshot of storageSnapshots) {
      releaseStorageCaptureSnapshot(this.device, snapshot, () => {
        captureCounters.gpuBuffersDestroyed++;
      });
    }
    this.releaseChannelSnapshot(channelSnapshot);
  }

  private createMeshUniformSnapshot(rasterContext: CaptureCompileContext["nativeRender"]): GPUBuffer | undefined {
    if (!rasterContext || rasterContext.geometry === "fullscreen") {
      return undefined;
    }
    const data = rasterContext.meshUniformData?.();
    const snapshot = data && new Float32Array(data);
    const buffer = createNativeMeshUniformBuffer(this.device, snapshot);
    if (buffer) {
      captureCounters.gpuBuffersCreated++;
    }
    return buffer;
  }
  private releaseMeshUniformSnapshot(buffer: GPUBuffer | undefined, submitted: boolean): void {
    if (!buffer) {
      return;
    }
    const destroy = () => {
      buffer.destroy?.();
      captureCounters.gpuBuffersDestroyed++;
    };
    if (!submitted) {
      destroy();
      return;
    }
    try {
      const pending = this.device.queue.onSubmittedWorkDone?.();
      if (pending) {
        void pending.then(destroy, destroy);
      } else {
        destroy();
      }
    } catch {
      destroy();
    }
  }

  private async resolveCapturePipeline(
    capture: CaptureRequest, commonCode: string | undefined, channels: SlangChannelBinding[], storage: StorageBindingNode[],
    generation: number, key: string, shouldContinue: () => boolean,
  ): Promise<CachedPipeline | null | undefined> {
    const cached = await this.getOrCompilePipeline(capture.captureShader, commonCode, channels, storage,
      generation, key, capture.debugPlan);
    if (!shouldContinue() || !this.isCompileContextCurrent(generation, key)) {
      // A newer batch needs capture too, so reissue rather than report a rejection.
      this.deferred = true;
      return undefined;
    }
    if (!cached) {
      this.recordPendingError(capture.varName);
    }
    return cached;
  }

  private submitCapture(
    capture: CaptureRequest, pipeline: GPURenderPipeline, bindGroup: GPUBindGroup,
    target: GPUTexture, targetView: GPUTextureView, sample: CaptureSample,
    nativeTarget: NativeRasterCaptureTarget | undefined, rasterContext: CaptureCompileContext["nativeRender"],
  ): number {
    const { gridWidth, gridHeight, bytesPerRow, captureCoord, isPixelMode, canvasWidth, canvasHeight } = sample;
    this.writeCaptureUniforms(captureCoord, gridWidth, gridHeight, capture.selectorIndex ?? 0, isPixelMode);

    const readbackBuffer = this.device.createBuffer({
      size: bytesPerRow * gridHeight,
      usage: (globalThis.GPUBufferUsage?.MAP_READ ?? 0x0001) | (globalThis.GPUBufferUsage?.COPY_DST ?? 0x0008),
    });
    captureCounters.gpuBuffersCreated++;

    try {
      const command = encodeVariableCapture(this.device, pipeline, bindGroup, target, targetView,
        readbackBuffer, { gridWidth, gridHeight, bytesPerRow, captureCoord, isPixelMode, canvasWidth, canvasHeight },
        nativeTarget, rasterContext);
      this.device.queue.submit([command]);
    } catch (error) {
      this.errors.record(error instanceof Error ? error.message : String(error), capture.varName);
      readbackBuffer.destroy();
      captureCounters.gpuBuffersDestroyed++;
      return 0;
    }

    const pending: PendingCapture = {
      varName: capture.varName,
      varType: capture.varType,
      buffer: readbackBuffer,
      gridWidth,
      gridHeight,
      bytesPerRow,
      resolved: false,
      discarded: false,
      destroyed: false,
      rgba: null,
      hidden: capture.hidden,
    };
    this.pendingCaptures.push(pending);
    this.beginReadback(pending);
    return 1;
  }

  private validateCaptureBatch(captures: CaptureRequest[]): boolean {
    const nativeCount = captures.filter(capture => capture.debugPlan?.nativeRender).length;
    if (nativeCount > 0 && !this.compileContext.nativeRender) {
      this.errors.record("A native raster context is required for this fragment capture.");
      return false;
    }
    if (nativeCount > 0 && nativeCount !== captures.length) {
      this.errors.record("Native raster and hook captures must be issued in separate batches.");
      return false;
    }
    const outputs = new Set(captures.map(capture => capture.debugPlan?.nativeRender?.output ?? 0));
    if (nativeCount > 0 && outputs.size > 1) {
      this.errors.record("Native MRT captures for different outputs must be issued in separate batches.");
      return false;
    }
    return true;
  }

  private captureResourcesReady(storage: StorageBindingNode[]): boolean {
    if (!this.resolveStorageBuffers(storage)) {
      this.recordPendingError();
      this.deferred = true;
      return false;
    }

    return true;
  }

  private resolveCaptureBindGroup(
    layout: GPUBindGroupLayout, channels: SlangChannelBinding[],
    resources: Array<{ slot: number; textureView: GPUTextureView; sampler?: GPUSampler }>, storage: StorageBindingNode[], storageBuffers: Map<string, GPUBuffer>, varName: string,
    meshUniformBuffer?: GPUBuffer,
    nativeRaster = false,
  ): GPUBindGroup | null {
    const nativeMesh = nativeRaster && this.compileContext.nativeRender?.geometry !== "fullscreen";
    const result = createCaptureBindGroup(
      this.device, layout, channels, resources, storage, storageBuffers, this.sampler,
      this.uniformBuffer, this.captureUniformBuffer, meshUniformBuffer, nativeMesh,
    );
    if (!result.group) {
      this.pendingError = result.error ?? "Capture bind group is not resolvable yet";
      this.deferred = true;
      this.recordPendingError(varName);
    }
    return result.group ?? null;
  }

  private captureChannelSnapshot(channels: SlangChannelBinding[]): { resources: Array<{ slot: number; textureView: GPUTextureView; sampler?: GPUSampler }>; textureCount: number; destroy(): void } | null {
    if (this.compileContext.captureChannelSnapshot) {
      const snapshot = this.compileContext.captureChannelSnapshot();
      if (!snapshot) {
        this.errors.record("Capture channels are not resolvable yet");
        this.deferred = true;
        return null;
      }
      captureCounters.gpuTexturesCreated += snapshot.textureCount;
      return snapshot;
    }
    const resources = channels.length > 0 ? this.getChannelResources?.(this.compileContext) ?? null : [];
    if (resources === null) {
      this.errors.record("Capture channels are not resolvable yet");
      this.deferred = true;
      return null;
    }
    return { resources, textureCount: 0, destroy: () => undefined };
  }

  private releaseChannelSnapshot(snapshot: { textureCount: number; destroy(): void }): void {
    if (snapshot.textureCount === 0) {
      return;
    }
    const destroy = () => {
      snapshot.destroy();
      captureCounters.gpuTexturesDestroyed += snapshot.textureCount;
    };
    // A feedback snapshot submitted its texture copies before capture
    // compilation. Even a later compile/resource failure must not destroy
    // those copies until that queued command has retired.
    try {
      const pending = this.device.queue.onSubmittedWorkDone?.();
      if (pending) {
        void pending.then(destroy, destroy);
      } else {
        destroy();
      }
    } catch {
      destroy();
    }
  }

  private writeFrameUniforms(channels: SlangChannelBinding[], uniforms: CaptureUniforms, width: number, height: number): void {
    const channelCount = getShaderToyChannelCount(channels);
    this.ensureUniformBuffers(channelCount);
    this.device.queue.writeBuffer(
      this.uniformBuffer!,
      0,
      packShaderToyUniforms({
        channelCount,
        width: width,
        height: height,
        time: uniforms.time,
        timeDelta: uniforms.timeDelta,
        frameRate: uniforms.frameRate,
        frame: uniforms.frame,
        mouse: uniforms.mouse,
        channelTime: uniforms.channelTime ?? new Array<number>(channelCount).fill(0),
        channelLoaded: uniforms.channelLoaded ?? new Array<number>(channelCount).fill(0),
        sampleRate: uniforms.sampleRate ?? 44100,
        date: uniforms.date,
        channelResolution: uniforms.channelResolution ?? new Array<number>(channelCount * 3).fill(0),
        cameraPos: uniforms.cameraPos,
        cameraDir: uniforms.cameraDir,
        vertexCount: uniforms.vertexCount,
        instanceCount: uniforms.instanceCount,
        viewMatrix: uniforms.camera?.view,
        projectionMatrix: uniforms.camera?.projection,
        viewProjection: uniforms.camera?.viewProjection,
      }, this.customUniforms, this.customUniforms),
    );

  }

  private beginReadback(pending: PendingCapture): void {
    const MAP_READ_MODE = globalThis.GPUMapMode?.READ ?? 0x0001;
    pending.buffer.mapAsync(MAP_READ_MODE)
      .then(() => {
        if (pending.discarded) {
          pending.buffer.unmap();
          this.destroyReadbackBuffer(pending);
          return;
        }
        const mapped = new Uint8Array(pending.buffer.getMappedRange()).slice();
        pending.buffer.unmap();
        this.destroyReadbackBuffer(pending);
        captureCounters.readbacksResolved++;
        // Strip the 256-byte row alignment into tight rows.
        const rowFloats = pending.gridWidth * RGBA_CHANNELS;
        const rgba = new Float32Array(rowFloats * pending.gridHeight);
        const strided = new Float32Array(mapped.buffer);
        const strideFloats = pending.bytesPerRow / FLOAT_BYTES;
        for (let row = 0; row < pending.gridHeight; row++) {
          rgba.set(strided.subarray(row * strideFloats, row * strideFloats + rowFloats), row * rowFloats);
        }
        pending.rgba = rgba;
        pending.resolved = true;
      })
      .catch(() => {
        pending.discarded = true;
        this.destroyReadbackBuffer(pending);
      });
  }

  private destroyReadbackBuffer(pending: PendingCapture): void {
    if (pending.destroyed) {
      return;
    }
    pending.buffer.destroy?.();
    pending.destroyed = true;
    captureCounters.gpuBuffersDestroyed++;
  }
  private async getOrCompilePipeline(
    captureShader: string,
    commonCode: string | undefined,
    channels: SlangChannelBinding[],
    storage: StorageBindingNode[],
    compileContextGeneration: number,
    compileContextKey: string,
    debugPlan?: DebugInstrumentationPlan,
  ): Promise<CachedPipeline | null> {
    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }
    const pipelineCacheKey = JSON.stringify([
      compileContextKey,
      debugPlan?.workspaceHash ?? "",
      debugPlan?.nativeRender ?? null,
      captureShader,
    ]);
    const existing = this.pipelineCache.get(pipelineCacheKey);
    if (existing) {
      existing.lastUsed = performance.now();
      return existing;
    }

    captureCounters.pipelineCompiles++;
    const result = await compileCapturePipeline(
      this.device, this.compiler, this.compileContext, this.customUniforms,
      captureShader, commonCode, channels, storage, debugPlan,
      () => this.isCompileContextCurrent(compileContextGeneration, compileContextKey),
    );
    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }
    if (!result.cached) {
      this.pendingError = result.error ?? "Capture pipeline creation failed";
      return null;
    }
    const cached = result.cached;
    this.cachePipeline(pipelineCacheKey, cached);
    return cached;
  }

  private cachePipeline(key: string, cached: CachedPipeline): void {
    if (this.pipelineCacheOrder.length >= SHADER_CACHE_MAX) {
      const oldest = this.pipelineCacheOrder.shift()!;
      this.pipelineCache.delete(oldest);
    }
    this.pipelineCache.set(key, cached);
    this.pipelineCacheOrder.push(key);
  }

  private isCompileContextCurrent(generation: number, contextKey: string): boolean {
    return !this.disposed &&
      generation === this.compileContextGeneration &&
      contextKey === this.compileContextKey;
  }


  private resolveStorageBuffers(storage: StorageBindingNode[]): Map<string, GPUBuffer> | null {
    const buffers = this.getStorageBuffers?.() ??
      this.compileContext.slangStorageBuffers ??
      new Map<string, GPUBuffer>();
    const missing = storage.find((node) => !buffers.has(node.name));
    if (missing) {
      this.pendingError = `Capture storage buffer "${missing.name}" is not resolvable yet`;
      return null;
    }
    return buffers;
  }

  private ensureUniformBuffers(channelCount: number): void {
    const UNIFORM = globalThis.GPUBufferUsage?.UNIFORM ?? 0x0040;
    const COPY_DST = globalThis.GPUBufferUsage?.COPY_DST ?? 0x0008;
    if (!this.uniformBuffer) {
      this.uniformBuffer = this.device.createBuffer({
        size: createSlangCustomUniformLayout(this.customUniforms, channelCount).size,
        usage: UNIFORM | COPY_DST,
      });
      captureCounters.gpuBuffersCreated++;
    }
    if (!this.captureUniformBuffer) {
      this.captureUniformBuffer = this.device.createBuffer({
        size: DBG_CAPTURE_UNIFORM_SIZE,
        usage: UNIFORM | COPY_DST,
      });
      captureCounters.gpuBuffersCreated++;
    }
    if (!this.sampler) {
      this.sampler = this.device.createSampler({ magFilter: "linear", minFilter: "linear" });
    }
  }

  private writeCaptureUniforms(
    captureCoord: [number, number],
    gridWidth: number,
    gridHeight: number,
    varIndex: number,
    isPixelMode: boolean,
  ): void {
    const buf = new ArrayBuffer(DBG_CAPTURE_UNIFORM_SIZE);
    const f32 = new Float32Array(buf);
    const i32 = new Int32Array(buf);
    f32[0] = captureCoord[0];
    f32[1] = captureCoord[1];
    f32[2] = gridWidth;
    f32[3] = gridHeight;
    i32[4] = varIndex | 0;
    i32[5] = isPixelMode ? 1 : 0;
    this.device.queue.writeBuffer(this.captureUniformBuffer!, 0, buf);
  }
}
