/// <reference types="@webgpu/types" />
import { buildSlangBindingPlan } from "./SlangBindingPlan";
import { slangChannelLayoutEntries, slangChannelResourceEntries } from "./SlangBindingResources";
import type {
  IVariableCapturer,
  CaptureCompileContext,
  CaptureCustomUniform,
  CaptureRequest,
  CaptureResult,
  CaptureUniforms,
} from "../capture/VariableCapturer";
import { allowNonUniformDerivatives } from "./wgslDiagnostics";
import type { ConfigInput, DebugInstrumentationPlan } from "@shader-studio/types";
import type { StorageBindingNode } from "../types/PassGraph";
import type { AsyncSlangCompiler } from "./AsyncSlangCompiler";
import type { SlangChannelBinding } from "./SlangPrelude";
import { DBG_CAPTURE_UNIFORM_SIZE, getShaderToyChannelCount } from "./SlangPrelude";
import { createSlangCustomUniformLayout, packShaderToyUniforms } from "./uniforms";
import { captureCounters, captureDiagTick } from "../capture/captureDiagnostics";
import { CaptureErrorLog, type CaptureError } from "../capture/CaptureErrorLog";
import { NativeRasterCaptureTarget } from "./NativeRasterCaptureTarget";
import { encodeVariableCapture, type CaptureSample } from "./VariableCaptureDraw";
import { captureCompileOptions, capturePipelineDescriptor } from "./NativeCapturePipeline";

const SHADER_CACHE_MAX = 20;
const FLOAT_BYTES = 4;
const RGBA_CHANNELS = 4;
const ROW_ALIGNMENT = 256;

interface CachedPipeline {
  pipeline: GPURenderPipeline;
  bindGroupLayout: GPUBindGroupLayout;
  lastUsed: number;
}

interface PendingCapture {
  varName: string;
  varType: string;
  buffer: GPUBuffer;
  gridWidth: number;
  gridHeight: number;
  bytesPerRow: number;
  resolved: boolean;
  discarded: boolean;
  destroyed: boolean;
  rgba: Float32Array | null;
  hidden?: boolean;
}

/**
 * WebGPU/Slang implementation of the variable-capture surface. Capture
 * shaders (generated by VariableCaptureBuilder in slang dialect) are
 * compiled to WGSL once per source, then drawn once per variable with the
 * selector index in the capture uniform block. Each draw renders to an
 * rgba32float target that is copied into a mappable buffer; collectResults
 * returns the captures whose buffer mapping has resolved.
 */
export class WebGPUVariableCapturer implements IVariableCapturer {
  private pipelineCache = new Map<string, CachedPipeline>();
  private pipelineCacheOrder: string[] = [];
  private pendingCaptures: PendingCapture[] = [];
  private pendingCaptureTargets = new Map<GPUTexture, GPUTexture | undefined>();
  private compileContext: CaptureCompileContext = {};
  private compileContextGeneration = 0;
  /** Set when an issue bailed on resources that were still resolving. */
  private deferred = false;
  private compileContextKey: string;
  private readonly errors = new CaptureErrorLog();
  /**
   * Compiling and binding happen in helpers that do not know which variable
   * they were called for, so they park the message here and the issue loop
   * attributes it to the capture in flight.
   */
  private pendingError: string | null = null;
  private uniformBuffer: GPUBuffer | null = null;
  private captureUniformBuffer: GPUBuffer | null = null;
  private sampler: GPUSampler | null = null;
  private customUniforms: CaptureCustomUniform[] = [];
  private disposed = false;

  constructor(
    private readonly device: GPUDevice,
    private readonly compiler: AsyncSlangCompiler,
    compileContext: CaptureCompileContext = {},
    private readonly getChannelResources?: (
      context: CaptureCompileContext,
    ) => Array<{ slot: number; textureView: GPUTextureView; sampler?: GPUSampler }> | null,
    private readonly getStorageBuffers?: () => Map<string, GPUBuffer>,
  ) {
    this.compileContext = compileContext;
    this.compileContextKey = this.getDeclarationContextKey(compileContext);
  }

  setCompileContext(context: CaptureCompileContext): void {
    const nextContextKey = this.getDeclarationContextKey(context);
    if (nextContextKey !== this.compileContextKey) {
      this.compileContextGeneration++;
      this.compileContextKey = nextContextKey;
      this.pipelineCache.clear();
      this.pipelineCacheOrder = [];
      this.uniformBuffer?.destroy?.();
      this.uniformBuffer = null;
    }
    this.compileContext = context;
  }

  setCustomUniforms(_declarations: string, uniforms: CaptureCustomUniform[]): void {
    const previousShape = JSON.stringify(this.customUniforms.map(({ name, type }) => ({ name, type })));
    const nextShape = JSON.stringify(uniforms.map(({ name, type }) => ({ name, type })));
    this.customUniforms = uniforms.map((uniform) => ({
      ...uniform,
      value: Array.isArray(uniform.value) ? [...uniform.value] : uniform.value,
    }));
    if (previousShape !== nextShape) {
      this.pipelineCache.clear();
      this.pipelineCacheOrder = [];
      this.uniformBuffer?.destroy?.();
      this.uniformBuffer = null;
    }
  }

  setInputBindings(_inputConfig: Record<string, ConfigInput>): void {
    // Channel views are resolved live via getChannelResources at issue time.
  }

  clearLastError(): void {
    this.errors.clear();
    this.pendingError = null;
    this.deferred = false;
  }

  /**
   * Channel views, storage buffers and the compile context are all resolved
   * live, so a batch can issue nothing simply because a pass rebuild has not
   * settled. That is not a capture failure - the caller retries it.
   */
  issueDeferred(): boolean {
    return this.deferred;
  }

  /** Files whatever a helper parked against the variable it failed for. */
  private recordPendingError(varName?: string): void {
    this.errors.record(this.pendingError, varName);
    this.pendingError = null;
  }

  getLastError(): string | null {
    return this.errors.lastMessage;
  }

  getCaptureErrors(): readonly CaptureError[] {
    return this.errors.list();
  }

  async issueCaptureAtPixel(
    captures: CaptureRequest[],
    pixelX: number,
    pixelY: number,
    canvasWidth: number,
    canvasHeight: number,
    uniforms: CaptureUniforms,
    shouldContinue: () => boolean = () => true,
  ): Promise<number> {
    // Convert top-left canvas coords into ShaderToy fragCoord space
    // (bottom-left origin, texel centre) — same mapping as the WebGL path.
    const captureCoord: [number, number] = [
      Math.floor(pixelX) + 0.5,
      canvasHeight - Math.floor(pixelY) - 1 + 0.5,
    ];
    return this.issue(captures, uniforms, 1, 1, captureCoord, true, canvasWidth, canvasHeight, shouldContinue);
  }

  async issueCaptureGrid(
    captures: CaptureRequest[],
    uniforms: CaptureUniforms,
    gridWidth: number,
    gridHeight: number,
    shouldContinue: () => boolean = () => true,
  ): Promise<number> {
    return this.issue(
      captures,
      uniforms,
      gridWidth,
      gridHeight,
      [0, 0],
      false,
      uniforms.res[0],
      uniforms.res[1],
      shouldContinue,
    );
  }

  collectResults(): CaptureResult[] {
    const results: CaptureResult[] = [];
    const remaining: PendingCapture[] = [];
    for (const pending of this.pendingCaptures) {
      if (pending.discarded) {
        continue;
      }
      if (pending.resolved && pending.rgba) {
        results.push({ varName: pending.varName, varType: pending.varType, rgba: pending.rgba, hidden: pending.hidden });
      } else {
        remaining.push(pending);
      }
    }
    this.pendingCaptures = remaining;
    return results;
  }

  cancelPendingCaptures(): void {
    for (const pending of this.pendingCaptures) {
      if (pending.resolved || pending.discarded) {
        continue;
      }
      pending.discarded = true;
    }
    if (this.pendingCaptures.length > 0) {
      captureDiagTick("capturer.cancel", {
        cancelledPending: this.pendingCaptures.length,
        buffersDestroyedNow: 0,
      });
    }
    this.pendingCaptures = [];
  }

  dispose(): void {
    this.disposed = true;
    this.compileContextGeneration++;
    this.cancelPendingCaptures();
    if (this.uniformBuffer) {
      this.uniformBuffer.destroy?.(); captureCounters.gpuBuffersDestroyed++;
    }
    this.uniformBuffer = null;
    if (this.captureUniformBuffer) {
      this.captureUniformBuffer.destroy?.(); captureCounters.gpuBuffersDestroyed++;
    }
    this.captureUniformBuffer = null;
    this.pipelineCache.clear();
    this.pipelineCacheOrder = [];
    for (const target of [...this.pendingCaptureTargets.keys()]) {
      this.destroyCaptureTarget(target);
    }
  }

  private async issue(
    captures: CaptureRequest[],
    uniforms: CaptureUniforms,
    gridWidth: number,
    gridHeight: number,
    captureCoord: [number, number],
    isPixelMode: boolean,
    canvasWidth: number,
    canvasHeight: number,
    shouldContinue: () => boolean,
  ): Promise<number> {
    this.clearLastError();
    if (captures.length === 0 || this.disposed) {
      return 0;
    }
    if (!this.validateCaptureBatch(captures)) {
      return 0;
    }
    const rasterContext = captures[0]?.debugPlan?.nativeRender ? this.compileContext.nativeRender : undefined;

    const channels = this.compileContext.slangChannels ?? [];
    const storage = this.compileContext.slangStorage ?? [];
    const commonCode = this.compileContext.commonCode;
    const compileContextGeneration = this.compileContextGeneration;
    const compileContextKey = this.compileContextKey;
    if (!this.captureResourcesReady(channels, storage)) {
      return 0;
    }

    this.writeFrameUniforms(channels, uniforms, rasterContext?.width ?? canvasWidth, rasterContext?.height ?? canvasHeight);

    const bytesPerRow = Math.ceil((gridWidth * RGBA_CHANNELS * FLOAT_BYTES) / ROW_ALIGNMENT) * ROW_ALIGNMENT;
    const { nativeTarget, target, targetView } = this.createCaptureTarget(rasterContext, gridWidth, gridHeight);

    let issued = 0;
    try {
      for (const capture of captures) {
        if (!shouldContinue() || this.disposed) {
          break;
        }

        const cached = await this.resolveCapturePipeline(capture, commonCode, channels, storage,
          compileContextGeneration, compileContextKey, shouldContinue);
        if (cached === undefined) {
          break;
        }
        if (cached === null) {
          continue;
        }

        const bindGroup = this.resolveCaptureBindGroup(cached.bindGroupLayout, channels, storage, capture.varName);
        if (!bindGroup) {
          continue;
        }

        issued += this.submitCapture(capture, cached.pipeline, bindGroup, target, targetView,
          { gridWidth, gridHeight, bytesPerRow, captureCoord, isPixelMode, canvasWidth, canvasHeight }, nativeTarget, rasterContext);

      }
    } finally {
      this.releaseCaptureTarget(target, nativeTarget, issued > 0);
    }

    captureCounters.capturesIssued += issued;
    captureDiagTick("capturer.issue", {
      pendingCaptures: this.pendingCaptures.length,
      pipelineCacheSize: this.pipelineCache.size,
      issuedThisCall: issued,
      gridW: gridWidth,
      gridH: gridHeight,
    });

    return issued;
  }

  private releaseCaptureTarget(target: GPUTexture, native: NativeRasterCaptureTarget | undefined, submitted: boolean): void {
    if (submitted) {
      this.destroyCaptureTargetAfterSubmittedWork(target, native?.depth);
      return;
    }
    if (native) {
      native.destroy();
    } else {
      target.destroy?.();
    }
    captureCounters.gpuTexturesDestroyed += native?.depth ? 2 : 1;
  }

  private async resolveCapturePipeline(
    capture: CaptureRequest, commonCode: string | undefined, channels: SlangChannelBinding[], storage: StorageBindingNode[],
    generation: number, key: string, shouldContinue: () => boolean,
  ): Promise<CachedPipeline | null | undefined> {
    const cached = await this.getOrCompilePipeline(capture.captureShader, commonCode, channels, storage,
      generation, key, capture.debugPlan);
    if (!shouldContinue() || !this.isCompileContextCurrent(generation, key)) {
      // A newer batch needs capture too, so reissue rather than report a rejection.
      this.deferred = true;
      return undefined;
    }
    if (!cached) {
      this.recordPendingError(capture.varName);
    }
    return cached;
  }

  private createCaptureTarget(rasterContext: CaptureCompileContext["nativeRender"], gridWidth: number, gridHeight: number) {
    const nativeTarget = rasterContext
      ? new NativeRasterCaptureTarget(this.device, rasterContext.width, rasterContext.height, rasterContext.geometry !== "fullscreen")
      : undefined;
    const target = nativeTarget?.texture ?? this.device.createTexture({
      label: "variable-capture target",
      size: { width: gridWidth, height: gridHeight },
      format: "rgba32float",
      usage: (globalThis.GPUTextureUsage?.RENDER_ATTACHMENT ?? 0x10) | (globalThis.GPUTextureUsage?.COPY_SRC ?? 0x01),
    });
    captureCounters.gpuTexturesCreated += nativeTarget?.depth ? 2 : 1;
    const targetView = nativeTarget?.view ?? target.createView();

    return { nativeTarget, target, targetView };
  }

  private submitCapture(
    capture: CaptureRequest, pipeline: GPURenderPipeline, bindGroup: GPUBindGroup,
    target: GPUTexture, targetView: GPUTextureView, sample: CaptureSample,
    nativeTarget: NativeRasterCaptureTarget | undefined, rasterContext: CaptureCompileContext["nativeRender"],
  ): number {
    const { gridWidth, gridHeight, bytesPerRow, captureCoord, isPixelMode, canvasWidth, canvasHeight } = sample;
    this.writeCaptureUniforms(captureCoord, gridWidth, gridHeight, capture.selectorIndex ?? 0, isPixelMode);

    const readbackBuffer = this.device.createBuffer({
      size: bytesPerRow * gridHeight,
      usage: (globalThis.GPUBufferUsage?.MAP_READ ?? 0x0001) | (globalThis.GPUBufferUsage?.COPY_DST ?? 0x0008),
    });
    captureCounters.gpuBuffersCreated++;

    try {
      const command = encodeVariableCapture(this.device, pipeline, bindGroup, target, targetView,
        readbackBuffer, { gridWidth, gridHeight, bytesPerRow, captureCoord, isPixelMode, canvasWidth, canvasHeight },
        nativeTarget, rasterContext);
      this.device.queue.submit([command]);
    } catch (error) {
      this.errors.record(error instanceof Error ? error.message : String(error), capture.varName);
      readbackBuffer.destroy();
      captureCounters.gpuBuffersDestroyed++;
      return 0;
    }

    const pending: PendingCapture = {
      varName: capture.varName,
      varType: capture.varType,
      buffer: readbackBuffer,
      gridWidth,
      gridHeight,
      bytesPerRow,
      resolved: false,
      discarded: false,
      destroyed: false,
      rgba: null,
      hidden: capture.hidden,
    };
    this.pendingCaptures.push(pending);
    this.beginReadback(pending);
    return 1;
  }

  private validateCaptureBatch(captures: CaptureRequest[]): boolean {
    const nativeCount = captures.filter(capture => capture.debugPlan?.nativeRender).length;
    if (nativeCount > 0 && !this.compileContext.nativeRender) {
      this.errors.record("A native raster context is required for this fragment capture.");
      return false;
    }
    if (nativeCount > 0 && nativeCount !== captures.length) {
      this.errors.record("Native raster and hook captures must be issued in separate batches.");
      return false;
    }
    return true;
  }

  private captureResourcesReady(channels: SlangChannelBinding[], storage: StorageBindingNode[]): boolean {
    const channelResources = channels.length > 0
      ? this.getChannelResources?.(this.compileContext) ?? null
      : [];
    if (channels.length > 0 && channelResources === null) {
      this.errors.record("Capture channels are not resolvable yet");
      this.deferred = true;
      return false;
    }
    if (!this.resolveStorageBuffers(storage)) {
      this.recordPendingError();
      this.deferred = true;
      return false;
    }

    return true;
  }

  private resolveCaptureBindGroup(
    layout: GPUBindGroupLayout, channels: SlangChannelBinding[], storage: StorageBindingNode[], varName: string,
  ): GPUBindGroup | null {
    const buffers = this.resolveStorageBuffers(storage);
    if (!buffers) {
      this.recordPendingError(varName);
      this.deferred = true;
      return null;
    }
    // Re-resolve after compilation: a pass rebuild can retire the original views.
    const resources = channels.length > 0 ? this.getChannelResources?.(this.compileContext) ?? null : [];
    if (resources === null) {
      this.errors.record("Capture channels are not resolvable yet", varName);
      this.deferred = true;
      return null;
    }
    const group = this.buildBindGroup(layout, channels, resources, storage, buffers);
    if (!group) {
      this.recordPendingError(varName);
    }
    return group;
  }

  private writeFrameUniforms(channels: SlangChannelBinding[], uniforms: CaptureUniforms, width: number, height: number): void {
    const channelCount = getShaderToyChannelCount(channels);
    this.ensureUniformBuffers(channelCount);
    this.device.queue.writeBuffer(
      this.uniformBuffer!,
      0,
      packShaderToyUniforms({
        channelCount,
        width: width,
        height: height,
        time: uniforms.time,
        timeDelta: uniforms.timeDelta,
        frameRate: uniforms.frameRate,
        frame: uniforms.frame,
        mouse: uniforms.mouse,
        channelTime: uniforms.channelTime ?? new Array<number>(channelCount).fill(0),
        channelLoaded: uniforms.channelLoaded ?? new Array<number>(channelCount).fill(0),
        sampleRate: uniforms.sampleRate ?? 44100,
        date: uniforms.date,
        channelResolution: uniforms.channelResolution ?? new Array<number>(channelCount * 3).fill(0),
        cameraPos: uniforms.cameraPos,
        cameraDir: uniforms.cameraDir,
        vertexCount: uniforms.vertexCount,
        instanceCount: uniforms.instanceCount,
        viewMatrix: uniforms.camera?.view,
        projectionMatrix: uniforms.camera?.projection,
        viewProjection: uniforms.camera?.viewProjection,
      }, this.customUniforms, this.customUniforms),
    );

  }

  private beginReadback(pending: PendingCapture): void {
    const MAP_READ_MODE = globalThis.GPUMapMode?.READ ?? 0x0001;
    pending.buffer.mapAsync(MAP_READ_MODE)
      .then(() => {
        if (pending.discarded) {
          pending.buffer.unmap();
          this.destroyReadbackBuffer(pending);
          return;
        }
        const mapped = new Uint8Array(pending.buffer.getMappedRange()).slice();
        pending.buffer.unmap();
        this.destroyReadbackBuffer(pending);
        captureCounters.readbacksResolved++;
        // Strip the 256-byte row alignment into tight rows.
        const rowFloats = pending.gridWidth * RGBA_CHANNELS;
        const rgba = new Float32Array(rowFloats * pending.gridHeight);
        const strided = new Float32Array(mapped.buffer);
        const strideFloats = pending.bytesPerRow / FLOAT_BYTES;
        for (let row = 0; row < pending.gridHeight; row++) {
          rgba.set(strided.subarray(row * strideFloats, row * strideFloats + rowFloats), row * rowFloats);
        }
        pending.rgba = rgba;
        pending.resolved = true;
      })
      .catch(() => {
        pending.discarded = true;
        this.destroyReadbackBuffer(pending);
      });
  }

  private destroyReadbackBuffer(pending: PendingCapture): void {
    if (pending.destroyed) {
      return;
    }
    pending.buffer.destroy?.();
    pending.destroyed = true;
    captureCounters.gpuBuffersDestroyed++;
  }

  private destroyCaptureTargetAfterSubmittedWork(target: GPUTexture, depth?: GPUTexture): void {
    this.pendingCaptureTargets.set(target, depth);
    try {
      const submittedWork = this.device.queue.onSubmittedWorkDone?.();
      if (!submittedWork) {
        this.destroyCaptureTarget(target);
        return;
      }
      void submittedWork.then(
        () => this.destroyCaptureTarget(target),
        () => this.destroyCaptureTarget(target),
      );
    } catch {
      this.destroyCaptureTarget(target);
    }
  }

  private destroyCaptureTarget(target: GPUTexture): void {
    if (!this.pendingCaptureTargets.has(target)) {
      return;
    }
    const depth = this.pendingCaptureTargets.get(target);
    this.pendingCaptureTargets.delete(target);
    target.destroy?.();
    depth?.destroy();
    captureCounters.gpuTexturesDestroyed += depth ? 2 : 1;
  }

  private async getOrCompilePipeline(
    captureShader: string,
    commonCode: string | undefined,
    channels: SlangChannelBinding[],
    storage: StorageBindingNode[],
    compileContextGeneration: number,
    compileContextKey: string,
    debugPlan?: DebugInstrumentationPlan,
  ): Promise<CachedPipeline | null> {
    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }
    const pipelineCacheKey = JSON.stringify([
      compileContextKey,
      debugPlan?.workspaceHash ?? "",
      captureShader,
    ]);
    const existing = this.pipelineCache.get(pipelineCacheKey);
    if (existing) {
      existing.lastUsed = performance.now();
      return existing;
    }

    captureCounters.pipelineCompiles++;
    const nativeRaster = debugPlan?.nativeRender && this.compileContext.nativeRender;
    const compileResult = await this.compiler.compile(captureShader,
      captureCompileOptions(this.compileContext, debugPlan, commonCode, channels, storage, this.customUniforms));

    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }
    if (!compileResult.success) {
      this.pendingError = this.captureCompileError(compileResult.errors, debugPlan);
      return null;
    }

    let pipeline: GPURenderPipeline;
    let bindGroupLayout: GPUBindGroupLayout;
    try {
      const shaderModule = this.device.createShaderModule({
        code: allowNonUniformDerivatives(compileResult.wgsl),
      });
      bindGroupLayout = this.device.createBindGroupLayout({
        entries: this.buildBindGroupLayoutEntries(channels, storage, Boolean(nativeRaster)),
      });
      const descriptor = capturePipelineDescriptor(
        this.device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] }), shaderModule,
        nativeRaster || undefined, debugPlan?.nativeRender?.fragmentEntryPoint);

      pipeline = this.device.createRenderPipelineAsync
        ? await this.device.createRenderPipelineAsync(descriptor)
        : this.device.createRenderPipeline(descriptor);
    } catch (error) {
      if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
        return null;
      }
      this.pendingError = error instanceof Error ? error.message : String(error);
      return null;
    }

    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }

    if (this.pipelineCacheOrder.length >= SHADER_CACHE_MAX) {
      const oldest = this.pipelineCacheOrder.shift()!;
      this.pipelineCache.delete(oldest);
    }
    const cached: CachedPipeline = { pipeline, bindGroupLayout, lastUsed: performance.now() };
    if (!this.isCompileContextCurrent(compileContextGeneration, compileContextKey)) {
      return null;
    }
    this.pipelineCache.set(pipelineCacheKey, cached);
    this.pipelineCacheOrder.push(pipelineCacheKey);
    return cached;
  }

  private captureCompileError(errors: string[], debugPlan?: DebugInstrumentationPlan): string {
    const selectedSource = debugPlan?.files.find((file) => file.uri === debugPlan.selectedSourceUri);
    const selectedLabel = selectedSource?.path ?? debugPlan?.selectedSourceUri;
    return errors
      .map((error) => selectedLabel && !error.includes(selectedLabel) && !error.includes(debugPlan!.selectedSourceUri)
        ? `${selectedLabel}: ${error}`
        : error)
      .join("\n");
  }

  private getDeclarationContextKey(context: CaptureCompileContext): string {
    return JSON.stringify([
      context.commonCode ?? "",
      context.slangChannels ?? [],
      context.slangStorage ?? [],
      context.slangPassName ?? "",
      context.slangModules ?? [],
      context.slangSourcePath ?? "",
      context.nativeRender ? {
        vertexEntryPoint: context.nativeRender.vertexEntryPoint,
        fragmentEntryPoint: context.nativeRender.fragmentEntryPoint,
        geometry: context.nativeRender.geometry,
      } : null,
    ]);
  }

  private isCompileContextCurrent(generation: number, contextKey: string): boolean {
    return !this.disposed &&
      generation === this.compileContextGeneration &&
      contextKey === this.compileContextKey;
  }

  /** Uniforms, unique channel resources, then pass-specific buffers. */
  private buildBindGroupLayoutEntries(
    channels: SlangChannelBinding[],
    storage: StorageBindingNode[],
    nativeRaster = false,
  ): GPUBindGroupLayoutEntry[] {
    const FRAGMENT = globalThis.GPUShaderStage?.FRAGMENT ?? 0x2;
    const VERTEX = globalThis.GPUShaderStage?.VERTEX ?? 0x1;
    const stageVisibility = nativeRaster ? VERTEX | FRAGMENT : FRAGMENT;
    const entries: GPUBindGroupLayoutEntry[] = [{
      binding: 0,
      visibility: VERTEX | FRAGMENT,
      buffer: { type: "uniform" },
    }];
    const plan = buildSlangBindingPlan(channels);
    entries.push(...slangChannelLayoutEntries(plan, stageVisibility));
    const storageBaseBinding = plan.nextBinding;
    for (const node of storage) {
      entries.push({
        binding: storageBaseBinding + node.binding,
        visibility: stageVisibility,
        buffer: { type: node.containsAtomic ? "storage" : "read-only-storage" },
      });
    }
    entries.push({
      binding: storageBaseBinding + storage.length,
      visibility: stageVisibility,
      buffer: { type: "uniform" },
    });
    return entries;
  }

  private buildBindGroup(
    layout: GPUBindGroupLayout,
    channels: SlangChannelBinding[],
    channelResources: Array<{ slot: number; textureView: GPUTextureView; sampler?: GPUSampler }>,
    storage: StorageBindingNode[],
    storageBuffers: Map<string, GPUBuffer>,
  ): GPUBindGroup | null {
    if (!this.uniformBuffer || !this.captureUniformBuffer) {
      // Both are created together in ensureUniformBuffers before the batch
      // starts; a miss here means dispose() raced the batch rather than a
      // real failure, so the caller has to retry it.
      this.deferred = true;
      this.pendingError = "Capture uniform buffers are not resolvable yet";
      return null;
    }
    const entries: GPUBindGroupEntry[] = [{ binding: 0, resource: { buffer: this.uniformBuffer } }];
    const plan = buildSlangBindingPlan(channels);
    const channelEntries = slangChannelResourceEntries(plan, channelResources, this.sampler);
    if (!channelEntries) {
      // The resolver can report "resolved, nothing yet" as an empty array
      // instead of null - e.g. mid pass-switch, before that pass's textures
      // are bound - which the null check above does not catch. The plan
      // still expects its channel slots, so this is the same not-ready
      // condition, not a permanent failure.
      this.deferred = true;
      this.pendingError = "Capture channel resources are not resolvable yet";
      return null;
    }
    entries.push(...channelEntries);
    const storageBaseBinding = plan.nextBinding;
    for (const node of storage) {
      entries.push({
        binding: storageBaseBinding + node.binding,
        resource: { buffer: storageBuffers.get(node.name)! },
      });
    }
    entries.push({
      binding: storageBaseBinding + storage.length,
      resource: { buffer: this.captureUniformBuffer },
    });
    try {
      return this.device.createBindGroup({ layout, entries });
    } catch (error) {
      this.pendingError = error instanceof Error ? error.message : String(error);
      return null;
    }
  }

  private resolveStorageBuffers(storage: StorageBindingNode[]): Map<string, GPUBuffer> | null {
    const buffers = this.getStorageBuffers?.() ??
      this.compileContext.slangStorageBuffers ??
      new Map<string, GPUBuffer>();
    const missing = storage.find((node) => !buffers.has(node.name));
    if (missing) {
      this.pendingError = `Capture storage buffer "${missing.name}" is not resolvable yet`;
      return null;
    }
    return buffers;
  }

  private ensureUniformBuffers(channelCount: number): void {
    const UNIFORM = globalThis.GPUBufferUsage?.UNIFORM ?? 0x0040;
    const COPY_DST = globalThis.GPUBufferUsage?.COPY_DST ?? 0x0008;
    if (!this.uniformBuffer) {
      this.uniformBuffer = this.device.createBuffer({
        size: createSlangCustomUniformLayout(this.customUniforms, channelCount).size,
        usage: UNIFORM | COPY_DST,
      });
      captureCounters.gpuBuffersCreated++;
    }
    if (!this.captureUniformBuffer) {
      this.captureUniformBuffer = this.device.createBuffer({
        size: DBG_CAPTURE_UNIFORM_SIZE,
        usage: UNIFORM | COPY_DST,
      });
      captureCounters.gpuBuffersCreated++;
    }
    if (!this.sampler) {
      this.sampler = this.device.createSampler({ magFilter: "linear", minFilter: "linear" });
    }
  }

  private writeCaptureUniforms(
    captureCoord: [number, number],
    gridWidth: number,
    gridHeight: number,
    varIndex: number,
    isPixelMode: boolean,
  ): void {
    const buf = new ArrayBuffer(DBG_CAPTURE_UNIFORM_SIZE);
    const f32 = new Float32Array(buf);
    const i32 = new Int32Array(buf);
    f32[0] = captureCoord[0];
    f32[1] = captureCoord[1];
    f32[2] = gridWidth;
    f32[3] = gridHeight;
    i32[4] = varIndex | 0;
    i32[5] = isPixelMode ? 1 : 0;
    this.device.queue.writeBuffer(this.captureUniformBuffer!, 0, buf);
  }
}
