export interface WgslIntrinsic {
  readonly name: string;
  readonly kind: "function" | "type" | "variable";
  readonly signature: string;
  readonly returnType?: string;
  readonly parameters: readonly { readonly name: string; readonly type: string }[];
  readonly description: string;
  readonly stages: readonly ("fragment" | "vertex" | "compute")[];
}

const ALL_STAGES = ["fragment", "vertex", "compute"] as const;
const COMPUTE = ["compute"] as const;

function fn(
  name: string,
  returnType: string,
  parameters: readonly [string, string][],
  description: string,
  stages: readonly ("fragment" | "vertex" | "compute")[] = ALL_STAGES,
): WgslIntrinsic {
  return Object.freeze({
    name,
    kind: "function" as const,
    signature: `${returnType} ${name}(${parameters.map(([type, parameter]) => `${type} ${parameter}`).join(", ")})`,
    returnType,
    parameters: Object.freeze(parameters.map(([type, parameter]) => Object.freeze({ name: parameter, type }))),
    description,
    stages,
  });
}

function builtinValue(
  name: string,
  type: string,
  description: string,
  stages: readonly ("fragment" | "vertex" | "compute")[],
): WgslIntrinsic {
  return Object.freeze({
    name,
    kind: "variable" as const,
    signature: `${type} ${name}`,
    returnType: type,
    parameters: Object.freeze([]),
    description,
    stages,
  });
}

const FRAGMENT = ["fragment"] as const;
const VERTEX = ["vertex"] as const;

/**
 * Closed WGSL built-in function catalogue from the spec's floating-point,
 * integer, comparison, derivative, texture, atomic, packing, and
 * synchronization sections. Overloads that differ only in operand width share
 * one entry each; texture sampling keeps its per-view overloads because
 * signature help must offer them.
 */
export const WGSL_INTRINSICS: readonly WgslIntrinsic[] = Object.freeze([
  fn("abs", "T", [["T", "x"]], "Component-wise absolute value."),
  fn("acos", "T", [["T", "x"]], "Component-wise arc cosine in radians."),
  fn("acosh", "T", [["T", "x"]], "Component-wise inverse hyperbolic cosine."),
  fn("asin", "T", [["T", "x"]], "Component-wise arc sine in radians."),
  fn("asinh", "T", [["T", "x"]], "Component-wise inverse hyperbolic sine."),
  fn("atan", "T", [["T", "x"]], "Component-wise arc tangent in radians."),
  fn("atan", "T", [["T", "y"], ["T", "x"]], "Component-wise arc tangent using the signs of both arguments."),
  fn("atanh", "T", [["T", "x"]], "Component-wise inverse hyperbolic tangent."),
  fn("ceil", "T", [["T", "x"]], "Rounds each component toward positive infinity."),
  fn("clamp", "T", [["T", "x"], ["T", "minValue"], ["T", "maxValue"]], "Constrains values to a range."),
  fn("cos", "T", [["T", "angle"]], "Cosine of an angle in radians."),
  fn("cosh", "T", [["T", "x"]], "Component-wise hyperbolic cosine."),
  fn("countLeadingZeros", "T", [["T", "x"]], "Number of leading zero bits in each component."),
  fn("countOneBits", "T", [["T", "x"]], "Number of one bits in each component."),
  fn("countTrailingZeros", "T", [["T", "x"]], "Number of trailing zero bits in each component."),
  fn("cross", "vec3f", [["vec3f", "x"], ["vec3f", "y"]], "Cross product of two 3D vectors."),
  fn("degrees", "T", [["T", "radians"]], "Converts radians to degrees."),
  fn("determinant", "f32", [["mat", "matrix"]], "Determinant of a square matrix."),
  fn("distance", "T", [["T", "p0"], ["T", "p1"]], "Distance between two points."),
  fn("dot", "T", [["vecN<T>", "x"], ["vecN<T>", "y"]], "Dot product of two vectors."),
  fn("dot4U8Packed", "u32", [["u32", "x"], ["u32", "y"]], "Four-way dot product of packed unsigned bytes, accumulated into a u32."),
  fn("dot4I8Packed", "i32", [["u32", "x"], ["u32", "y"]], "Four-way dot product of packed signed bytes, accumulated into an i32."),
  fn("exp", "T", [["T", "x"]], "Natural exponential of each component."),
  fn("exp2", "T", [["T", "x"]], "Base-2 exponential of each component."),
  fn("extractBits", "T", [["T", "x"], ["u32", "offset"], ["u32", "count"]], "Extracts a bit range from each component."),
  fn("faceForward", "T", [["T", "x"], ["T", "y"], ["T", "z"]], "Flips x to face away from the surface when needed."),
  fn("firstLeadingBit", "T", [["T", "x"]], "Bit position of the most significant one (or zero) bit."),
  fn("firstTrailingBit", "T", [["T", "x"]], "Bit position of the least significant one bit."),
  fn("floor", "T", [["T", "x"]], "Rounds each component toward negative infinity."),
  fn("fma", "T", [["T", "x"], ["T", "y"], ["T", "z"]], "Fused multiply-add: x * y + z with a single rounding."),
  fn("fract", "T", [["T", "x"]], "Fractional part of each component."),
  fn("frexp", "__frexpResult", [["T", "x"]], "Splits each component into a normalized fraction and a base-2 exponent."),
  fn("insertBits", "T", [["T", "x"], ["T", "y"], ["u32", "offset"], ["u32", "count"]], "Inserts a bit range from y into x."),
  fn("inverseSqrt", "T", [["T", "x"]], "Reciprocal square root of each component."),
  fn("ldexp", "T", [["T", "x"], ["i32", "exp"]], "Builds x * 2^exp from a fraction and an exponent."),
  fn("length", "T", [["vecN<T>", "x"]], "Euclidean length of a vector."),
  fn("log", "T", [["T", "x"]], "Natural logarithm of each component."),
  fn("log2", "T", [["T", "x"]], "Base-2 logarithm of each component."),
  fn("max", "T", [["T", "x"], ["T", "y"]], "Component-wise maximum."),
  fn("min", "T", [["T", "x"], ["T", "y"]], "Component-wise minimum."),
  fn("mix", "T", [["T", "x"], ["T", "y"], ["T", "a"]], "Linear interpolation between x and y."),
  fn("mix", "T", [["T", "x"], ["T", "y"], ["f32", "a"]], "Linear interpolation between x and y with a scalar blend factor."),
  fn("modf", "__modfResult", [["T", "x"]], "Splits each component into fractional and whole parts."),
  fn("normalize", "T", [["vecN<T>", "x"]], "Unit vector in the direction of x."),
  fn("pow", "T", [["T", "x"], ["T", "y"]], "x raised to the power y, component-wise."),
  fn("quantizeToF16", "T", [["T", "x"]], "Quantizes each component to f16 precision without changing the type."),
  fn("radians", "T", [["T", "degrees"]], "Converts degrees to radians."),
  fn("reflect", "T", [["vecN<T>", "incident"], ["vecN<T>", "normal"]], "Reflection direction for an incident vector and surface normal."),
  fn("refract", "T", [["vecN<T>", "incident"], ["vecN<T>", "normal"], ["f32", "eta"]], "Refraction direction for an incident vector, normal, and index ratio."),
  fn("reverseBits", "T", [["T", "x"]], "Reverses the bits of each component."),
  fn("round", "T", [["T", "x"]], "Rounds each component to the nearest integer, ties away from zero."),
  fn("saturate", "T", [["T", "x"]], "Clamps each component to the 0 to 1 range."),
  fn("select", "T", [["T", "x"], ["T", "y"], ["bool", "condition"]], "Selects x or y per component from a scalar condition."),
  fn("select", "T", [["T", "x"], ["T", "y"], ["vecN<bool>", "condition"]], "Selects x or y per component from a vector condition."),
  fn("all", "bool", [["vecN<bool>", "e"]], "True when every component is true."),
  fn("any", "bool", [["vecN<bool>", "e"]], "True when any component is true."),
  fn("bitcast", "T", [["S", "e"]], "Reinterprets the bits of a value as another type of the same size."),
  fn("sign", "T", [["T", "x"]], "Sign of each component: -1, 0, or 1."),
  fn("sin", "T", [["T", "angle"]], "Sine of an angle in radians."),
  fn("sinh", "T", [["T", "x"]], "Component-wise hyperbolic sine."),
  fn("smoothstep", "T", [["T", "low"], ["T", "high"], ["T", "x"]], "Smooth Hermite interpolation between two edges."),
  fn("sqrt", "T", [["T", "x"]], "Square root of each component."),
  fn("step", "T", [["T", "edge"], ["T", "x"]], "0 when x is below the edge, 1 otherwise."),
  fn("tan", "T", [["T", "angle"]], "Tangent of an angle in radians."),
  fn("tanh", "T", [["T", "x"]], "Component-wise hyperbolic tangent."),
  fn("transpose", "matMxN<T>", [["matNxM<T>", "matrix"]], "Matrix transpose."),
  fn("trunc", "T", [["T", "x"]], "Truncates each component toward zero."),
  fn("dpdx", "T", [["T", "x"]], "Partial derivative in the window x direction."),
  fn("dpdxCoarse", "T", [["T", "x"]], "Coarse partial derivative in the window x direction."),
  fn("dpdxFine", "T", [["T", "x"]], "Fine partial derivative in the window x direction."),
  fn("dpdy", "T", [["T", "x"]], "Partial derivative in the window y direction."),
  fn("dpdyCoarse", "T", [["T", "x"]], "Coarse partial derivative in the window y direction."),
  fn("dpdyFine", "T", [["T", "x"]], "Fine partial derivative in the window y direction."),
  fn("fwidth", "T", [["T", "x"]], "Sum of absolute window-space derivatives."),
  fn("fwidthCoarse", "T", [["T", "x"]], "Coarse sum of absolute window-space derivatives."),
  fn("fwidthFine", "T", [["T", "x"]], "Fine sum of absolute window-space derivatives."),
  fn("arrayLength", "u32", [["ptr<storage, array<E>>", "pointer"]], "Runtime element count of a storage-buffer array."),
  fn("atomicLoad", "T", [["ptr<workgroup, atomic<T>>", "pointer"]], "Atomically loads the atomic value."),
  fn("atomicStore", "void", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically stores a value."),
  fn("atomicAdd", "T", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically adds and returns the old value."),
  fn("atomicSub", "T", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically subtracts and returns the old value."),
  fn("atomicMax", "T", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically takes the maximum and returns the old value."),
  fn("atomicMin", "T", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically takes the minimum and returns the old value."),
  fn("atomicAnd", "T", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically ANDs and returns the old value."),
  fn("atomicOr", "T", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically ORs and returns the old value."),
  fn("atomicXor", "T", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically XORs and returns the old value."),
  fn("atomicExchange", "T", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "value"]], "Atomically exchanges and returns the old value."),
  fn("atomicCompareExchangeWeak", "__atomicCompareExchangeResult", [["ptr<workgroup, atomic<T>>", "pointer"], ["T", "compare"], ["T", "value"]], "Atomically compares and exchanges, reporting the old value and success."),
  fn("textureSample", "vec4f", [["texture_2d<T>", "t"], ["sampler", "s"], ["vec2f", "coords"]], "Samples a 2D texture with implicit derivatives."),
  fn("textureSample", "vec4f", [["texture_cube<T>", "t"], ["sampler", "s"], ["vec3f", "coords"]], "Samples a cube texture with implicit derivatives."),
  fn("textureSample", "vec4f", [["texture_2d_array<T>", "t"], ["sampler", "s"], ["vec2f", "coords"], ["u32", "array_index"]], "Samples a 2D texture array with implicit derivatives."),
  fn("textureSample", "vec4f", [["texture_3d<T>", "t"], ["sampler", "s"], ["vec3f", "coords"]], "Samples a 3D texture with implicit derivatives."),
  fn("textureSampleBias", "vec4f", [["texture_2d<T>", "t"], ["sampler", "s"], ["vec2f", "coords"], ["f32", "bias"]], "Samples a 2D texture with an explicit mip bias."),
  fn("textureSampleLevel", "vec4f", [["texture_2d<T>", "t"], ["sampler", "s"], ["vec2f", "coords"], ["f32", "level"]], "Samples a 2D texture at an explicit mip level."),
  fn("textureSampleLevel", "vec4f", [["texture_2d_array<T>", "t"], ["sampler", "s"], ["vec2f", "coords"], ["u32", "array_index"], ["f32", "level"]], "Samples a 2D texture array at an explicit mip level."),
  fn("textureSampleGrad", "vec4f", [["texture_2d<T>", "t"], ["sampler", "s"], ["vec2f", "coords"], ["vec2f", "ddx"], ["vec2f", "ddy"]], "Samples a 2D texture with explicit gradients."),
  fn("textureSampleCompare", "f32", [["texture_depth_2d", "t"], ["sampler_comparison", "s"], ["vec2f", "coords"], ["f32", "depth_ref"]], "Depth comparison sample on a 2D depth texture."),
  fn("textureSampleCompareLevel", "f32", [["texture_depth_2d", "t"], ["sampler_comparison", "s"], ["vec2f", "coords"], ["f32", "depth_ref"]], "Depth comparison sample at mip level zero."),
  fn("textureGather", "vec4f", [["texture_2d<T>", "t"], ["sampler", "s"], ["vec2f", "coords"]], "Gathers the four texels around the sample point."),
  fn("textureGather", "vec4f", [["u32", "component"], ["texture_2d<T>", "t"], ["sampler", "s"], ["vec2f", "coords"]], "Gathers one component from the four surrounding texels."),
  fn("textureGatherCompare", "vec4f", [["texture_depth_2d", "t"], ["sampler_comparison", "s"], ["vec2f", "coords"], ["f32", "depth_ref"]], "Gathers four depth comparison results."),
  fn("textureLoad", "vec4<T>", [["texture_2d<T>", "t"], ["vec2u", "coords"], ["u32", "level"]], "Loads one texel without sampling."),
  fn("textureLoad", "vec4<T>", [["texture_storage_2d<F, A>", "t"], ["vec2u", "coords"]], "Loads one texel from a storage texture."),
  fn("textureStore", "void", [["texture_storage_2d<F, write>", "t"], ["vec2u", "coords"], ["vec4<T>", "value"]], "Stores one texel into a storage texture."),
  fn("textureDimensions", "vec2u", [["texture_2d<T>", "t"]], "Dimensions of a 2D texture in texels."),
  fn("textureDimensions", "vec2u", [["texture_2d<T>", "t"], ["u32", "level"]], "Dimensions of one mip level of a 2D texture."),
  fn("textureDimensions", "u32", [["texture_storage_2d<F, A>", "t"]], "Dimensions of a storage texture in texels."),
  fn("textureNumLayers", "u32", [["texture_2d_array<T>", "t"]], "Layer count of a texture array."),
  fn("textureNumLayers", "u32", [["texture_cube_array<T>", "t"]], "Layer count of a cube texture array."),
  fn("textureNumLevels", "u32", [["texture_2d<T>", "t"]], "Mip level count of a texture."),
  fn("textureNumSamples", "u32", [["texture_multisampled_2d<T>", "t"]], "Sample count of a multisampled texture."),
  fn("pack4x8snorm", "u32", [["vec4f", "x"]], "Packs four floats into signed normalized bytes."),
  fn("pack4x8unorm", "u32", [["vec4f", "x"]], "Packs four floats into unsigned normalized bytes."),
  fn("pack2x16snorm", "u32", [["vec2f", "x"]], "Packs two floats into signed normalized half words."),
  fn("pack2x16unorm", "u32", [["vec2f", "x"]], "Packs two floats into unsigned normalized half words."),
  fn("pack2x16float", "u32", [["vec2f", "x"]], "Packs two f32 values into f16 bit patterns."),
  fn("unpack4x8snorm", "vec4f", [["u32", "x"]], "Unpacks signed normalized bytes into floats."),
  fn("unpack4x8unorm", "vec4f", [["u32", "x"]], "Unpacks unsigned normalized bytes into floats."),
  fn("unpack2x16snorm", "vec2f", [["u32", "x"]], "Unpacks signed normalized half words into floats."),
  fn("unpack2x16unorm", "vec2f", [["u32", "x"]], "Unpacks unsigned normalized half words into floats."),
  fn("unpack2x16float", "vec2f", [["u32", "x"]], "Unpacks f16 bit patterns into f32 values."),
  fn("storageBarrier", "void", [], "Orders storage-buffer accesses across the workgroup."),
  fn("workgroupBarrier", "void", [], "Synchronizes workgroup execution and memory."),
  fn("textureBarrier", "void", [], "Orders storage-texture accesses across the workgroup."),
  fn("workgroupUniformLoad", "T", [["ptr<workgroup, T>", "pointer"]], "Reads a workgroup value uniformly across the workgroup.", COMPUTE),
  fn("subgroupAdd", "T", [["T", "e"]], "Adds a value across all active invocations in the subgroup.", COMPUTE),
  fn("subgroupExclusiveAdd", "T", [["T", "e"]], "Exclusive subgroup prefix sum of a value.", COMPUTE),
  fn("subgroupInclusiveAdd", "T", [["T", "e"]], "Inclusive subgroup prefix sum of a value.", COMPUTE),
  fn("subgroupMul", "T", [["T", "e"]], "Multiplies a value across all active invocations in the subgroup.", COMPUTE),
  fn("subgroupExclusiveMul", "T", [["T", "e"]], "Exclusive subgroup prefix product of a value.", COMPUTE),
  fn("subgroupInclusiveMul", "T", [["T", "e"]], "Inclusive subgroup prefix product of a value.", COMPUTE),
  fn("subgroupMin", "T", [["T", "e"]], "Minimum of a value across all active invocations in the subgroup.", COMPUTE),
  fn("subgroupMax", "T", [["T", "e"]], "Maximum of a value across all active invocations in the subgroup.", COMPUTE),
  fn("subgroupAnd", "T", [["T", "e"]], "Bitwise AND of a value across all active invocations in the subgroup.", COMPUTE),
  fn("subgroupOr", "T", [["T", "e"]], "Bitwise OR of a value across all active invocations in the subgroup.", COMPUTE),
  fn("subgroupXor", "T", [["T", "e"]], "Bitwise XOR of a value across all active invocations in the subgroup.", COMPUTE),
  fn("subgroupAll", "bool", [["bool", "e"]], "True when a predicate holds for every active invocation in the subgroup.", COMPUTE),
  fn("subgroupAny", "bool", [["bool", "e"]], "True when a predicate holds for any active invocation in the subgroup.", COMPUTE),
  fn("subgroupBallot", "vec4u", [["bool", "predicate"]], "Bitmask of the active subgroup invocations satisfying a predicate.", COMPUTE),
  fn("subgroupBroadcast", "T", [["T", "value"], ["u32", "sourceLaneIndex"]], "Broadcasts a value from one subgroup lane to every active invocation.", COMPUTE),
  fn("subgroupBroadcastFirst", "T", [["T", "value"]], "Broadcasts a value from the first active subgroup lane.", COMPUTE),
  fn("subgroupElect", "bool", [], "True for the active invocation with the lowest subgroup lane index.", COMPUTE),
  fn("subgroupShuffle", "T", [["T", "value"], ["u32", "sourceLaneIndex"]], "Reads a value from another subgroup lane by index.", COMPUTE),
  fn("subgroupShuffleDown", "T", [["T", "value"], ["u32", "delta"]], "Reads a value from the lane delta positions above in the subgroup.", COMPUTE),
  fn("subgroupShuffleUp", "T", [["T", "value"], ["u32", "delta"]], "Reads a value from the lane delta positions below in the subgroup.", COMPUTE),
  fn("subgroupShuffleXor", "T", [["T", "value"], ["u32", "mask"]], "Reads a value from the lane whose index is XORed with a mask.", COMPUTE),
  fn("quadBroadcast", "T", [["T", "value"], ["u32", "id"]], "Broadcasts a value from one lane of the quad to the whole quad.", COMPUTE),
  fn("quadSwapX", "T", [["T", "value"]], "Swaps a value between quad lanes in the X direction.", COMPUTE),
  fn("quadSwapY", "T", [["T", "value"]], "Swaps a value between quad lanes in the Y direction.", COMPUTE),
  fn("quadSwapDiagonal", "T", [["T", "value"]], "Swaps a value between diagonally opposite quad lanes.", COMPUTE),
  builtinValue("global_invocation_id", "vec3u", "Global workgroup-grid coordinates of the current invocation.", COMPUTE),
  builtinValue("local_invocation_id", "vec3u", "Coordinates of the current invocation within its workgroup.", COMPUTE),
  builtinValue("local_invocation_index", "u32", "Linear index of the current invocation within its workgroup.", COMPUTE),
  builtinValue("workgroup_id", "vec3u", "Coordinates of the current workgroup in the dispatch grid.", COMPUTE),
  builtinValue("num_workgroups", "vec3u", "Number of workgroups in the dispatch.", COMPUTE),
  builtinValue("workgroup_size", "vec3u", "Workgroup dimensions from the @workgroup_size attribute.", COMPUTE),
  builtinValue("subgroup_invocation_id", "u32", "Lane index of the current invocation within its subgroup; needs enable subgroups.", COMPUTE),
  builtinValue("subgroup_size", "u32", "Number of invocations in the current subgroup; needs enable subgroups.", COMPUTE),
  builtinValue("num_subgroups", "u32", "Number of subgroups in the workgroup; needs the subgroup_id extension.", COMPUTE),
  builtinValue("position", "vec4f", "Framebuffer position of the current fragment.", FRAGMENT),
  builtinValue("front_facing", "bool", "True when the fragment belongs to a front-facing primitive.", FRAGMENT),
  builtinValue("frag_depth", "f32", "Output depth value written by the fragment shader.", FRAGMENT),
  builtinValue("sample_index", "u32", "Sample index of the current fragment invocation.", FRAGMENT),
  builtinValue("sample_mask", "u32", "Input sample mask of the current fragment invocation.", FRAGMENT),
  builtinValue("vertex_index", "u32", "Index of the current vertex.", VERTEX),
  builtinValue("instance_index", "u32", "Index of the current instance.", VERTEX),
]);

export function findWgslIntrinsics(name: string): readonly WgslIntrinsic[] {
  return WGSL_INTRINSICS.filter((intrinsic) => intrinsic.name === name);
}
