name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "mkdocs.yml"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
